### ISSUE TITLE
Failing after BBBTurnAutoScaling: Resource creation Initiated

### ISSUE THREAD

**Issue by abhinavprateek** [aws-samples/aws-scalable-big-blue-button-example#1]
**Describe the bug**
The TurnServer Autoscaling group fails to start

**To Reproduce**
1. Launch using the automated script (setup.sh) with the required option

2. Once the BBBTurnStack deployement is underway, it will crash with the below error

Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

**Expected behavior**
Successful completion and launch of TurnServer AutoScaling

**Screenshots**
https://imgur.com/a/Hdaty2Q

**Comment by couchgott** [comment]
Hi abhinavprateek, 

can you log into the EC2 instance while the deployment is ongoing (using Systems Manager's Session Manager) and post the output of the  /var/log/cloud-init-output.log log file. 

i tried to reproduce your error with the current code but could deploy the turn server successfully. 

Ty! 

David

**Comment by abhinavprateek** [comment]
Thanks for quick revert @couchgott 

Output logs: 
Start
![Screenshot from 2020-09-16 19-576-31](https://user-images.githubusercontent.com/8946513/93351878-db1a5280-f857-11ea-9f55-3758c5afda23.png)

It get doing the same command repeatedly 
![Screenshot from 20208-09-16 19-55-55](https://user-images.githubusercontent.com/8946513/93352157-29c7ec80-f858-11ea-8c10-23035f63bea7.png)

End of log:
![Screenshot from 2020-09-16 20-06-06](https://user-images.githubusercontent.com/8946513/93352187-33515480-f858-11ea-8a6b-7d695197fdf3.png)

After this the deployment status changes to ROLLBACK_IN_PROGRESS

**Comment by couchgott** [comment]
Hi, 

did you setup the subdomain accordently to redirect to route53? 
when i try to evaluate the DNS servers related to your domain i can see they're still non-AWS DNS servers. 

; <<>> DiG 9.10.6 <<>> testbbb.codeemple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 2761
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;testbbb.codeemple.com.		IN	A

;; AUTHORITY SECTION:
com.			900	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1600268496 1800 900 604800 86400

;; Query time: 63 msec
;; SERVER: 172.16.173.64#53(172.16.173.64)
;; WHEN: Wed Sep 16 17:01:59 CEST 2020
;; MSG SIZE  rcvd: 123


Which prevents the auto registration with route53 to be public available. 

you might setup the NS entries at your original codeemple.com for the testbbb subdomain to point to the DNS Servers shown at the Hosted Zone (console) in Route53. 

let me know if this helps ;) 

Cheers!

David

**Comment by abhinavprateek** [comment]
My bad, again!!!!

Added the NS from route53 only to the godaddy subdomain
![ksnip_20200916-231109](https://user-images.githubusercontent.com/8946513/93372786-0742cd00-f872-11ea-9b46-aa5928416f60.png)

On the godaddy side
![ksnip_20200916-231135](https://user-images.githubusercontent.com/8946513/93372818-132e8f00-f872-11ea-9b29-861a637e95de.png)


Or do i need to change the NS for the main domain along with subdomain?

**Comment by couchgott** [comment]
Hey, that should be it. you do not need to set the DNS for the plain domain. setting it for the sub is (usually) enough. 

be patient after the first deployment. DNS delay/caching might end up you not being able to access right away. (also on IP changes of the main urls conference.xxxxx.tld

just give it some minutes :) 

to be sure check route53 if the Host A / Cnames has been added.

**Comment by abhinavprateek** [comment]
conference.xxxx.tld not responding but able to ping it which is getting resolved to a elb url (xxx.ap-south-1.elb.amazonaws.com)

Also, trying to access via the name resolution for ping doesn't work (xxx.ap-south-1.elb.amazonaws.com)

No worries about ip and real name, thses are all dummy accounts

**Comment by couchgott** [comment]
i do have a working url though: so you should be good in a few minutes as well;)  
![image](https://user-images.githubusercontent.com/1948953/93375485-81feee80-f858-11ea-88f6-a703916e99bc.png)

**Comment by abhinavprateek** [comment]
got it working. appreciate your help.

Will add a PR later with all these changes in case someone else need it

**Comment by couchgott** [comment]
Happy that it worked. Looking forward to your contribution and thanks for your feedback!

**Comment by abhinavprateek** [comment]
just one more thing, how to find the bbb secret and url api to integrate with any application? or is it saved in aws secret manager?

**Comment by couchgott** [comment]
All secrets can be found at the Secrets Manager. That's also the place where the components are pulling the secrets from.

**Comment by Corradones** [comment]
Hi all.
The exactly same error for me.

1)I have my own domain in ovh, let's say www.domain.com. So in my ovh dns i create a subdomain called "abc.domain.com" .
2)In Route53 i created a new hostedzone called "domain.com" (with no subrecord called abc, just domain.com)
3)In ovh i've made abc.domain.com to point to the four dns addresses that route53 gave me in myhosted zone
when i try to deploy it stops at same identical point (Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.)
During installation the script create in route53 automatically a record called tu-xyzsefgwf.domain.com with the right public ip of turn instance (and then cancel it in rollback procedure when all the stack fails)
Note: whan i launch script i write abc.domain.com (and not only domain.com).

Am i messing with someting? I'm going crazy

Ready to post every screenshot you need , thanks

![immagine](https://user-images.githubuse
![Schermata a 2020-09-30 12-10-19](https://user-images.githubusercontent.com/72140228/94687875-212de680-032d-11eb-967d-3c79fa400e88.png)
rcontent.com/72140228/94687203-39e9cc80-032c-11eb-9192-54264d36d501.png)

**Comment by couchgott** [comment]
Hi Corradones, 

as follows: if you want to use a subdomain like abc.domain.com for instance for conference.abc.domain.com you'll need to create abc.domain.com as Hosted Zone in Route53. 

If you do not have registered domain.com with Route53/AWS you'll need to add the DNS Servers for the Route53 hosted Zone into the DNS of domain.com at your responsible DNS Servers. 

like:

abc.domain.com. NS ns1.aws....

abc.domain.com. NS ns2.aws....

abc.domain.com. NS ns3.aws....
...

whatever name Route53 is giving you as NS entries. 

Then you need to check if the entries got published, you might have a delay due DNS TTL settings. 
you can use nslookup or dig for that. 

like:

`nslookup
DefaultServer:  XXXXXXXXXXX
Address: XXXXXXX

> set type=NS
> google.com
Server: XXXX
Address:  XXXXXXXXXXX

Answer:
google.de       nameserver = ns1.google.com
google.de       nameserver = ns3.google.com
google.de       nameserver = ns2.google.com
google.de       nameserver = ns4.google.com`

put in the subdomain you are using. 

if the answer contains the DNS Servers from the Hosted Zone you're using you're fine to go. 

if you gonna use the top domain like: conference.domain.com you'll basically need todo the same but with your main domain. 
careful. if you have other services running besides the BBB deployment you might have to migrate the DNS completely to Route53. 
So in most cases using a sub domain would be my suggestion. 

for further troubleshooting use Systems Manager (Session Manager) to log into your turn instance during deployment and look into the /var/log/cloud-init-output.log ... if you see the instance hanging around at the DNS check most likely your DNS settings at your DNS servers are not correct.

**Comment by Corradones** [comment]
thanks a lot. Let me check. I reply you asap

**Comment by Corradones** [comment]
It works !

Ovh subdomain creation was ok
ovh NS pointing to aws ns was ok

My mistake was this: the name of hosted zone
My hostedzone was set (wrongly!) as "domain.com" and not as "abc.domain.com".
I was setting the record "abc.domain.com" like an A record (wrong!) inside the "domain.com" hosted zone

For readers: hostedzone must have the same name of the address you want to point to it (also if in texbox description aws suggests to insert just the main domain). The script create  some new DNS record among which the famous "conference.abc.domain.com". 

NB. to reach greelinght you must insert the "https://" before.

Thanks a lot couchgott (i hope to receive further helps by you in my next study-days)

**Comment by AwaleRohin** [comment]
Got into the same issue and could not apply the solutions provided above. 
My configuration:
`hosted zone` : `myDomain.com`
`BBBDomainName` :`meeting.myDomain.com`

Both are available at route53. What am I missing here?

**Comment by wsamipw** [comment]
> Got into the same issue and could not apply the solutions provided above.
> My configuration:
> `hosted zone` : `myDomain.com`
> `BBBDomainName` :`meeting.myDomain.com`
> 
> Both are available at route53. What am I missing here?
> 
> Edit: Stack failed after being stuck at this log state
> 
> ```
> + grep -m 1 'has address 13.126.225.66'
> + sleep 5
> + host tu-5l26l4.meeting.myDomain.com
> + grep -m 1 'has address 13.126.225.66'
> + sleep 5
> + host tu-5l26l4.meeting.myDomain.com
> + grep -m 1 'has address 13.126.225.66'
> + sleep 5
> ```

Got into exactly same issue.

**Comment by iamkhalidbashir** [comment]
> > Got into the same issue and could not apply the solutions provided above.
> > My configuration:
> > `hosted zone` : `myDomain.com`
> > `BBBDomainName` :`meeting.myDomain.com`
> > Both are available at route53. What am I missing here?
> > Edit: Stack failed after being stuck at this log state
> > ```
> > + grep -m 1 'has address 13.126.225.66'
> > + sleep 5
> > + host tu-5l26l4.meeting.myDomain.com
> > + grep -m 1 'has address 13.126.225.66'
> > + sleep 5
> > + host tu-5l26l4.meeting.myDomain.com
> > + grep -m 1 'has address 13.126.225.66'
> > + sleep 5
> > ```
> 
> Got into exactly same issue.

Got in exact issue
