### ISSUE TITLE
Add EC2 Image Builder Pipeline to create AMIs for application instances and turn servers to enhance scaling speed

### ISSUE THREAD

**Issue by couchgott** [aws-samples/aws-scalable-big-blue-button-example#102]
Currently the Big Blue Button App and Turn Servers are installing on the fly if the ASG is scaling-out the environment (or instances are replaced)
This can take up to 45min for an instance to be ready to serve meetings. 

the plan is to pre-create the AMIs and use these when scaling.

this will need an EC2 Image Builder Pipeline with components and automation docs as well as changes how and where to alter via UserData at the actual instance bootstrap. 

also we need some definition for lifecycle rules and the way we do utilize the ami finder might change as well.

**Comment by FlipOsky** [comment]
y all the time happening like this, now all are join herein this discussion  and fix the life plan.. unnecessary I'm suffering a lotz.
