### ISSUE TITLE
Check if docker daemon is running in setup.sh script

### ISSUE THREAD

**Issue by bklein1** [aws-samples/aws-scalable-big-blue-button-example#104]
**Describe the bug**
When using the setup.sh script without a docker daemon running, this step fails, but the script just continues. This leads to a deployment failure of the frontend ECS tasks

**To Reproduce**
1. Terminate you local docker daemon
2. Use the setup.sh script
3. Check that there is no images in ECR
4. See that the Frontend Stack will not successfully finish deployment

**Expected behavior**
Break the execution of the setup.sh script with a concise error message

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by ed8962** [comment]
Is there a solution to this? My deployment fails at the ECS tasks even though I have performed all the steps in the guide.
