### ISSUE TITLE
1000 users in one server

### ISSUE THREAD

**Issue by sudra-parth** [aws-samples/aws-scalable-big-blue-button-example#111]
Hello Geeks,

I am using the c5n.18xlarge instance for bigbluebutton. And my use case is to add 1500 users approx in one session that is one room at a time for 1 hour. When the students count reaches 600 my bigbluebutton will start lagging and three dots will appear in the screen.

Is there any suggested solution to use more than 1000 users in one meeting at a time?

Thank you in advance.

**Comment by jonnyfux** [comment]
Hi @sudra-parth, 

first of all impressive that you manage to get 600 users in one BBB Meeting. That is on of the highest numbers I’ve heard of. BBB is however not designed to host that many people in one room (over multiple rooms no problem). You can try using a Bare metal server e.g. c5d.metal but I still doubt that you will get to 1500 users. Also those server comes at a crazy price tag. It might be cheaper to integrate Zoom which btw also only support 1000 users in a meeting. Also all other commercial system have a limit of 1000 users (Cisco webex, teams). Anything beyond that is a Webinar which is essential a live stream. 

In General I would think about your use case again. Videoconferencing is meant for interaction and collaboration  which I can’t image being possible with that many users. Maybe you should be looking at other alternatives. For example a live stream with a Chat functionality for your use case like Twitch or YouTube Live. If you wanna host it your self you cold look at the Slido and wowza combination. But there are many options. 

I hope this gives you some help for your use case. 

Good look!

**Comment by bklein1** [comment]
Hi @sudra-parth,

I agree with @jonnyfux. In the BBB FAQ the recommendation is 150 users as a maximum per session. The c5d.metal or c5d.24xlarge have 96 vCPU which is more than the c5n.18xlarge has, but with the caveat of "only" 25 Gbps network bandwidth. It is hard to estimate if that would be enough for your use case.

**Comment by couchgott** [comment]
Hey @sudra-parth 
i think your use-case is more towards casting a stream of your webinar somewhere else like with this plugin: https://github.com/manishkatyan/bbb-streaming or simply with an RMTP stream to have it in a 1:N setup working.
BBB itself is more towards video conferencing than to webinars on scale like it sounds you are targeting to (like my mates already mentioned)
The topic also might be better discussed with the BBB folks directly. they're very helpful but mit just give you the same/similar answer. 
everything over 500+ attendees in a single meeting is a big challenge not only for BBB and especially the NodeJS part of the application and its context switching (afaik!) but also for each clients bandwith as video/audio might habe to be transported to each of them eating up a lot of bandwith as well. 

the topic is addressed and some more ideas and information can be found here: https://github.com/bigbluebutton/bigbluebutton/issues/8295 

Hopefully it helps ;) 

Cheers!
