### ISSUE TITLE
AWS EC2 TargetGroup Targets Health Status Is Draining

### ISSUE THREAD

**Issue by ReflexFox** [aws-samples/aws-scalable-big-blue-button-example#117]
![image](https://user-images.githubusercontent.com/42571543/189327606-4d768292-b565-46f7-87c9-22af892f9913.png)

**Comment by couchgott** [comment]
Hi,

please check whats the status of your ECS services and tasks. if they're stopped or in a restart cycle, check their logs for errors. 

Best, 

David

**Comment by couchgott** [comment]
closing due inactivity
