### ISSUE TITLE
Integration with Moodle LMS

### ISSUE THREAD

**Issue by virilc** [aws-samples/aws-scalable-big-blue-button-example#119]
Consider adding a section to the document on how to integrate this solution to a popular Learning Management System (LMS) like Moodle.

Once [BBB plugin](https://moodle.org/plugins/mod_bigbluebuttonbn) is installed (Moodle v4 already has this integrated, no need to install), take note of the following to properly configure the plugin:

BigBlueButton Server URL: https://scalelite.FQDN ... example: https://scalite.bbb.example.com
BigBlueButton Shared Secret: Check AWS Secrets Manager (**BBBLoadbalancerSecret**), **Secret value** of the **basekeyvalue** key

**Comment by couchgott** [comment]
closing as added to v4.5.0 as readme and parameters ;)
