### ISSUE TITLE
Use reasonable cluster size for ECS

### ISSUE THREAD

**Issue by bklein1** [aws-samples/aws-scalable-big-blue-button-example#12]
**Is your feature request related to a problem? Please describe.**
There is unnecessary cost in a minimal setup, because 1 EC2 instance is in idle and 2 are just under minimal usage.

**Describe the solution you'd like**
Removing the 3 EC2 instance and scaling down the other 2. But remain enough resources to update both services.

**Comment by couchgott** [comment]
utilizing the capacity provider will help here. so we put desired to 1 instance as default and max to 3 for the sample setup. this will make sure the system will be upgradable due CP requesting additional instances if needed. will put these changes into the next pull request.

**Comment by couchgott** [comment]
solved by #39
