### ISSUE TITLE
The following resource(s) failed to create: [DBClusterEventSubscription]

### ISSUE THREAD

**Issue by kmoh19** [aws-samples/aws-scalable-big-blue-button-example#121]
I get the following error  when i run the setup.sh file

#Error saving credentials: error storing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``

#Embedded stack arn:aws:cloudformation:eu-west-1:541631110155:stack/bbb-stack-BBBDatabaseStack-1E0UYU7NHRPHW/b2862140-7641-11ed-9957-02df677fc455 was not successfully created: The following resource(s) failed to create: [DBClusterEventSubscription]

and then 

#The following resource(s) failed to create: [BBBDatabaseStack, BBBTurnStack]. Rollback requested by user.

and then a complete rollback.

on second run

#Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

#Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
#The following resource(s) failed to create: [BBBTurnAutoScaling]

Kindly help.

[stack_error.log](https://github.com/aws-samples/aws-scalable-big-blue-button-example/files/10178190/stack_error.log)
[stack_error_second_run.log](https://github.com/aws-samples/aws-scalable-big-blue-button-example/files/10178544/stack_error_second_run.log)

**Comment by kmoh19** [comment]
found the resolution in earlier logged issue https://github.com/aws-samples/aws-scalable-big-blue-button-example/issues/1

**Comment by couchgott** [comment]
thank you for letting me know ;)

**Comment by kmoh19** [comment]
this is fantastic work by the way! this is all new territory for me so this is a great resource. many thanks for sharing!
