### ISSUE TITLE
Auto Scaling not installing the BigBlue Application on new instance

### ISSUE THREAD

**Issue by ojhaashish13** [aws-samples/aws-scalable-big-blue-button-example#122]
**Describe the bug**
I am using Serverless deployment for Greenlight and Scalelite and tried to add another Greenlight instance using ASG. 
I have updated the ASG desired, Minimum, and Maximum capacities to 2 but the new server only copied the BigBlue files  and the application is not running there. It said the bigblue application is not installed when I ran conf check command.

```
root@ip:/var# bbb-conf --status
 BigBlueButton does not appear to be installed.  Could not
 locate: /etc/bigbluebutton/bigbluebutton-release
```

**To Reproduce**
1. Go to ASG in AWS console.
2. Click on  Edit and update the desired, Minimum, and Maximum capacities to 2
3. Once the new instance is up and running, login into the instance.
4. Run the "bbb-conf --status" and it said that "BigBlueButton does not appear to be installed"

**Expected behavior**
It should create another BigBlue instance and should run the application by copying all the configurations.

**Comment by couchgott** [comment]
Hi @ojhaashish13 , 

the greenlight container does not contain the big blue button application by itself. this is just the frontend to manage and access meetings. the actual BBB application is placed at the Big Blue Button application instances. 
so when you want to scale and add big blue button meeting instances you should raise the count of instances in the bbb instance ASG. 

Hope this helps, 

best, 

david

**Comment by ojhaashish13** [comment]
Thanks for the quick reply. 
While deployment I have used mentioned settings for application instances:
    
_"BBBApplicationMaxInstances": 1,
    "BBBApplicationMinInstances": 1,
    "BBBApplicationDesiredInstances": 1_

After deployment, I can see 2 ASGs in my console.
1. [test-stack-BBBAppStack-#########-BBBApplicationAutoScaling-########]
2. [test-stack-BBBTurnStack-#########-BBBTurnAutoScaling-#########]

I have modified the "BBBApplicationAutoScaling" with desired, Minimum, and Maximum capacities to 2. And in few minutes it added another "BBBApplicationStack-bbbonaws" instance.

When I login into these instances on the first instance have BBB Application running but on the new instance I can see te "/var/bigbluebutton" folder with all bigblue files but BBB application is not installed and running on there.

Please help me which configuration, I have to update to add another application instance.

 Screenshot attached.
![Screenshot 2023-01-11 at 8 40 21 AM](https://user-images.githubusercontent.com/6647624/211821197-699168b1-bf46-4547-8d10-c88ca8d73994.png)
![Screenshot 2023-01-11 at 8 42 25 AM](https://user-images.githubusercontent.com/6647624/211821648-9a34f5ce-d7c2-45df-b680-4c175b03191c.png)
![Screenshot 2023-01-11 at 8 44 48 AM](https://user-images.githubusercontent.com/6647624/211821953-fe968d9c-b76c-48b6-958d-a8c6b11c8910.png)

**Comment by couchgott** [comment]
there should be a log of the bootstrap process within /var/log/cloud-init-output.log. 
please check
also be sure that you left the instance for 15-20min for bbb to successfully and fully being installed. it takes a while. 

best.

**Comment by ojhaashish13** [comment]
There are some issues with the installation. I have compared logs of both application instances and both run the same processes but the second server file "/var/log/cloud-init-output.log" states that there is some issue while installing the ubuntu packages and it failed. 

`Get:68 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-requests-toolbelt all 0.8.0-1.1 [35.2 kB]
Get:69 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-tz all 2019.3-1ubuntu0.20.04.0 [24.5 kB]
Get:70 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-rfc3339 all 1.1-2 [6808 B]
Get:71 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-acme all 1.1.0-1 [29.6 kB]
Get:72 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-configargparse all 0.13.0-2 [22.6 kB]
Err:73 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-future all 0.18.2-2
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:74 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-parsedatetime all 2.4-5
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:75 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.hookable amd64 5.0.0-1build1
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:76 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.event all 4.4-2build1
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:77 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.component all 4.3.0-3
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:78 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3-certbot all 0.40.0-1ubuntu0.1
  503  Service Unavailable [IP: 54.190.18.91 80]
Ign:79 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu1.5
Ign:80 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3.8-dev amd64 3.8.10-0ubuntu1~20.04.6
Err:81 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-dev amd64 3.8.2-0ubuntu2
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:82 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-icu amd64 2.4.2-0ubuntu3
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:83 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-wheel all 0.34.2-1
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:84 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3-pip all 20.0.2-5ubuntu1.6
  503  Service Unavailable [IP: 54.190.18.91 80]
Err:85 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 certbot all 0.40.0-1ubuntu0.1
  503  Service Unavailable [IP: 54.190.18.91 80]
Get:79 http://security.ubuntu.com/ubuntu focal-updates/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu1.5 [155 kB]
Get:80 http://security.ubuntu.com/ubuntu focal-updates/main amd64 python3.8-dev amd64 3.8.10-0ubuntu1~20.04.6 [514 kB]
Fetched 60.6 MB in 41s (1467 kB/s)
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/p/python-future/python3-future_0.18.2-2_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/p/parsedatetime/python3-parsedatetime_2.4-5_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/z/zope.hookable/python3-zope.hookable_5.0.0-1build1_amd64.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/z/zope.event/python3-zope.event_4.4-2build1_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/z/zope.component/python3-zope.component_4.3.0-3_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/p/python-certbot/python3-certbot_0.40.0-1ubuntu0.1_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/p/python3-defaults/python3-dev_3.8.2-0ubuntu2_amd64.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/main/p/pyicu/python3-icu_2.4.2-0ubuntu3_amd64.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/w/wheel/python3-wheel_0.34.2-1_all.deb  503  Service Unavailable [IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/p/python-pip/python3-pip_20.0.2-5ubuntu1.6_all.deb  503  Service Unavailable[IP: 54.190.18.91 80]
E: Failed to fetch http://us-west-2.ec2.archive.ubuntu.com/ubuntu/pool/universe/p/python-certbot/certbot_0.40.0-1ubuntu0.1_all.deb  503  Service Unavailable[IP: 54.190.18.91 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Cloud-init v. 22.4.2-0ubuntu0~20.04.2 running 'modules:final' at Fri, 13 Jan 2023 05:05:48 +0000. Up 20.39 seconds.
2023-01-13 05:08:31,625 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2023-01-13 05:08:31,625 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 22.4.2-0ubuntu0~20.04.2 finished at Fri, 13 Jan 2023 05:08:31 +0000. Datasource DataSourceEc2Local.  Up 183.42 seconds`

Please guide me on how to fix this. As I am assuming as per the readme both instances should run the application.

`**Setting up the Big Blue Button Application Instance(s): bbb-on-aws-bbbappscalable.template.yaml(for single server deployments bbb-on-aws-bbbappsingle.template.yaml)

Finally we will deploy the Big Blue Button application instances. Each instance is basically a separate video conference system.**`

**Comment by ojhaashish13** [comment]
No, I am not using NAT Gateway or private subnets, just run the setup script with all the standard configurations mentioned in JSON.
This is the output of apt update command.

root@ip:/var/snap/amazon-ssm-agent/6312# apt update
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2325 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1014 kB]
Fetched 3674 kB in 2s (1525 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
root@ip:/var/snap/amazon-ssm-agent/6312#

**Comment by couchgott** [comment]
if you now run apt install certbot .. does it work? 
i tested in my dev enviroment and successfully scaled up the application instance. so generally the code does work from my perspective ,)

**Comment by ojhaashish13** [comment]
It throwing an error. 

root@ip-:/var/snap/amazon-ssm-agent/6312# run apt install certbot
Command 'run' not found, did you mean:
  command 'rue' from snap darkdimension-rue (0.3.0)
  command 'zun' from deb python3-zunclient (4.0.0-0ubuntu1)
  command 'runq' from deb exim4-daemon-heavy (4.93-13ubuntu1.7)
  command 'runq' from deb exim4-daemon-light (4.93-13ubuntu1.7)
  command 'runq' from deb sendmail-bin (8.15.2-18)
  command 'runc' from deb runc (1.1.0-0ubuntu1~20.04.2)
  command 'rup' from deb rstat-client (4.0.1-9)
  command 'crun' from deb crun (0.12.1+dfsg-1)
  command 'rn' from deb trn4 (4.0-test77-12)
  command 'grun' from deb grun (0.9.3-2)
  command 'zrun' from deb moreutils (0.63-1)
  command 'srun' from deb slurm-client (19.05.5-1)

See 'snap info <snapname>' for additional versions.


It seems the **userdata** of the template [](https://github.com/aws-samples/aws-scalable-big-blue-button-example/blob/main/templates/bbb-on-aws-bbbappscalable.template.yaml) didn't execute on this instance

**Comment by couchgott** [comment]
run ist not a command on ubuntu: 'apt install certbot' should be the command

**Comment by ojhaashish13** [comment]
Oops, my bad. Please see the output.

root@ip-:/var/snap/amazon-ssm-agent/6312# apt install certbot
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  python3-acme python3-certbot python3-configargparse python3-future python3-icu python3-josepy python3-mock python3-parsedatetime python3-pbr
  python3-requests-toolbelt python3-rfc3339 python3-tz python3-zope.component python3-zope.event python3-zope.hookable
Suggested packages:
  python3-certbot-apache python3-certbot-nginx python-certbot-doc python-acme-doc python-future-doc python-mock-doc
The following NEW packages will be installed:
  certbot python3-acme python3-certbot python3-configargparse python3-future python3-icu python3-josepy python3-mock python3-parsedatetime python3-pbr
  python3-requests-toolbelt python3-rfc3339 python3-tz python3-zope.component python3-zope.event python3-zope.hookable
0 upgraded, 16 newly installed, 0 to remove and 0 not upgraded.
Need to get 916 kB/1152 kB of archives.
After this operation, 6066 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-future all 0.18.2-2 [336 kB]
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-parsedatetime all 2.4-5 [32.6 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.hookable amd64 5.0.0-1build1 [11.2 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.event all 4.4-2build1 [7704 B]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/universe amd64 python3-zope.component all 4.3.0-3 [38.3 kB]
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3-certbot all 0.40.0-1ubuntu0.1 [223 kB]
Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal/main amd64 python3-icu amd64 2.4.2-0ubuntu3 [250 kB]
Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/universe amd64 certbot all 0.40.0-1ubuntu0.1 [17.9 kB]
Fetched 916 kB in 0s (8319 kB/s)
Selecting previously unselected package python3-josepy.
(Reading database ... 90593 files and directories currently installed.)
Preparing to unpack .../00-python3-josepy_1.2.0-2_all.deb ...
Unpacking python3-josepy (1.2.0-2) ...
Selecting previously unselected package python3-pbr.
Preparing to unpack .../01-python3-pbr_5.4.5-0ubuntu1_all.deb ...
Unpacking python3-pbr (5.4.5-0ubuntu1) ...
Selecting previously unselected package python3-mock.
Preparing to unpack .../02-python3-mock_3.0.5-1build1_all.deb ...
Unpacking python3-mock (3.0.5-1build1) ...
Selecting previously unselected package python3-requests-toolbelt.
Preparing to unpack .../03-python3-requests-toolbelt_0.8.0-1.1_all.deb ...
Unpacking python3-requests-toolbelt (0.8.0-1.1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../04-python3-tz_2019.3-1ubuntu0.20.04.0_all.deb ...
Unpacking python3-tz (2019.3-1ubuntu0.20.04.0) ...
Selecting previously unselected package python3-rfc3339.
Preparing to unpack .../05-python3-rfc3339_1.1-2_all.deb ...
Unpacking python3-rfc3339 (1.1-2) ...
Selecting previously unselected package python3-acme.
Preparing to unpack .../06-python3-acme_1.1.0-1_all.deb ...
Unpacking python3-acme (1.1.0-1) ...
Selecting previously unselected package python3-configargparse.
Preparing to unpack .../07-python3-configargparse_0.13.0-2_all.deb ...
Unpacking python3-configargparse (0.13.0-2) ...
Selecting previously unselected package python3-future.
Preparing to unpack .../08-python3-future_0.18.2-2_all.deb ...
Unpacking python3-future (0.18.2-2) ...
Selecting previously unselected package python3-parsedatetime.
Preparing to unpack .../09-python3-parsedatetime_2.4-5_all.deb ...
Unpacking python3-parsedatetime (2.4-5) ...
Selecting previously unselected package python3-zope.hookable.
Preparing to unpack .../10-python3-zope.hookable_5.0.0-1build1_amd64.deb ...
Unpacking python3-zope.hookable (5.0.0-1build1) ...
Selecting previously unselected package python3-zope.event.
Preparing to unpack .../11-python3-zope.event_4.4-2build1_all.deb ...
Unpacking python3-zope.event (4.4-2build1) ...
Selecting previously unselected package python3-zope.component.
Preparing to unpack .../12-python3-zope.component_4.3.0-3_all.deb ...
Unpacking python3-zope.component (4.3.0-3) ...
Selecting previously unselected package python3-certbot.
Preparing to unpack .../13-python3-certbot_0.40.0-1ubuntu0.1_all.deb ...
Unpacking python3-certbot (0.40.0-1ubuntu0.1) ...
Selecting previously unselected package python3-icu.
Preparing to unpack .../14-python3-icu_2.4.2-0ubuntu3_amd64.deb ...
Unpacking python3-icu (2.4.2-0ubuntu3) ...
Selecting previously unselected package certbot.
Preparing to unpack .../15-certbot_0.40.0-1ubuntu0.1_all.deb ...
Unpacking certbot (0.40.0-1ubuntu0.1) ...
Setting up python3-configargparse (0.13.0-2) ...
Setting up python3-requests-toolbelt (0.8.0-1.1) ...
Setting up python3-icu (2.4.2-0ubuntu3) ...
Setting up python3-zope.event (4.4-2build1) ...
Setting up python3-pbr (5.4.5-0ubuntu1) ...
update-alternatives: using /usr/bin/python3-pbr to provide /usr/bin/pbr (pbr) in auto mode
Setting up python3-tz (2019.3-1ubuntu0.20.04.0) ...
Setting up python3-mock (3.0.5-1build1) ...
Setting up python3-zope.hookable (5.0.0-1build1) ...
Setting up python3-josepy (1.2.0-2) ...
Setting up python3-future (0.18.2-2) ...
update-alternatives: using /usr/bin/python3-futurize to provide /usr/bin/futurize (futurize) in auto mode
update-alternatives: using /usr/bin/python3-pasteurize to provide /usr/bin/pasteurize (pasteurize) in auto mode
Setting up python3-rfc3339 (1.1-2) ...
Setting up python3-parsedatetime (2.4-5) ...
Setting up python3-zope.component (4.3.0-3) ...
Setting up python3-acme (1.1.0-1) ...
Setting up python3-certbot (0.40.0-1ubuntu0.1) ...
Setting up certbot (0.40.0-1ubuntu0.1) ...
Created symlink /etc/systemd/system/timers.target.wants/certbot.timer → /lib/systemd/system/certbot.timer.
Processing triggers for man-db (2.9.1-1) ...
root@ip-:/var/snap/amazon-ssm-agent/6312#

**Comment by couchgott** [comment]
this looks like it's installing correct now. 
not sure where the issue comes from. i was not able to restore / replicate that behavior in any of my test deployments. 
in which region are you deploying to? 

best,

D.

**Comment by ojhaashish13** [comment]
I am using US West (Oregon). The issue is resolved after manually running the user-data scripts mentioned in the template **bbb-on-aws-bbbappscalable.template.yaml** and then restarting the services.
