### ISSUE TITLE
Preinstall Certbot and configure it to renew certificate with Let's Encrypt

### ISSUE THREAD

**Issue by metaldaniel** [aws-samples/aws-scalable-big-blue-button-example#123]
I had this setup working but after 3 months the certs expire and I had to install certbot.
Pre-install this and configure this to auto-renew the certs.

**Comment by couchgott** [comment]
Hi @metaldaniel,

the certbot and let's encrypt install are part of the automatic bbb-install.sh and so the issue might be related to what version of big blue button you setup back then. 
this is not part of this repo/cloudformation and scripts. 
best would be to ask at: https://github.com/bigbluebutton/bbb-install for advice. 

Best,

D.

**Comment by couchgott** [comment]
closing here.
