### ISSUE TITLE
How could I connect to AWS Fargate or Scalelite containers?

### ISSUE THREAD

**Issue by hernanlozano93** [aws-samples/aws-scalable-big-blue-button-example#125]
**Is your feature request related to a problem? Please describe.**
How could I access the AWS Fargate or the containers to review the information and the corresponding recordings.

**Describe the solution you'd like**
Being able to connect through some means to the containers or to the information that is registered there.

**Describe alternatives you've considered**
I have tried with the session-manager-plugin but I have not been able to, in the same way through the AWS CLI but since the ExecuteCommand option is not enabled, it does not allow entry,

**Comment by hernanlozano93** [comment]
Hi @couchgott,

I need to see the recordings log, the recordings and the list of recordings, however, when I enter the EFS nothing appears, it is as if it is empty. I can see the recordings through scalelite and they are being recorded from LMS Moodle. 

Additionally, the turn server and the app server are turned off at night and on weekends, to save costs, so when I enter the server, when it restarts, the BBB session records are deleted, but I guess that these are stored in the EFS.

**Comment by couchgott** [comment]
The recordings log should be on the actual BBB Instance not one of the containers. there is a script triggered by BBB when a meeting ends which transfers the video to the EFS filesystem after encoding. 

afterwards the recording is removed from the instance. 

you can use "df" on the instance OS to identify where the EFS is mounted. 

Does this help?

Best,

David

**Comment by couchgott** [comment]
closing due inactivity
