### ISSUE TITLE
Update scripts for greenlight v3

### ISSUE THREAD

**Issue by Valthonis2712** [aws-samples/aws-scalable-big-blue-button-example#126]
can this cloudformation script be updated to support the implementation of Greenlight V3 with BBB 2.6 in AWS scalable options? We have been unsuccessful in implementing the new greenlight in the serverless capacity and scaling the 2.6 prod version with greenlight v2 in serverless.

**Comment by couchgott** [comment]
Hey @Valthonis2712 

i will test as soon as possible. and adjust the code if needed

best, 

David

**Comment by Valthonis2712** [comment]
Hi, Just seeing if there's an update or ETA on these changes at all. Thx for your awesome support and work!

**Comment by couchgott** [comment]
Hi @Valthonis2712 

i started building the new version here: https://github.com/aws-samples/aws-scalable-big-blue-button-example/tree/5.0.0 
i am still facing a bug where the initial password is not set when deploying (need to exec into the task/container and set the password manually) as well as testing is not finished. 
currently i am very busy but i hope i will get the last issues solved by  end of may. 

Best, 

David

**Comment by Valthonis2712** [comment]
Thx for the update! Thank you also for your support and awesome work!

**Comment by couchgott** [comment]
This is now fixed in the 5.0.0 release of the deployment example. (please read the changelog for details)
