### ISSUE TITLE
Manuall installation

### ISSUE THREAD

**Issue by RedaElHajjaji** [aws-samples/aws-scalable-big-blue-button-example#128]
can someone pleas help me do this manually, without cloudFormation i want the the installation of this architecture from the start to finish but manually if that makes sense...

please, and thanks.

**Comment by couchgott** [comment]
Hey @RedaElHajjaji, 

this will be a looong description. 
Do you want to deploy manually the whole environment including the dynamic scaling or which option do you look into?
If, there are quite a things todo. 
Best approach would be to go through the Cloudformation templates in the order they're deployed from the root stack. 
then check each resource deployed and adapt manually the creation in the different Services affected. 

Best, 

David

**Comment by RedaElHajjaji** [comment]
okay, is the "Template structure and deployment workflow" section containe the cloudformation templates in order?

**Comment by RedaElHajjaji** [comment]
@couchgott can you please help me with it, on where i should start..?

**Comment by couchgott** [comment]
hi,

dorry for the delay but i am vacationing right now.

best is to look into the yaml template files at the root folder of the project.

one is deploying the needed ecr registry and another the s3 bucket to place container images and scripts used for bootstrapping. doing all manually you can also refer to e.g docker hub directly and use the scripts manually depending on your needs. most scripts are used to orchestrate when scaling.
the root template yaml you can use to see which template order is used zo deploy and you can then walk through each nested template to see the needed resources strp by step. hope thid helps. best David

**Comment by RedaElHajjaji** [comment]
Hey, hope you're doing well

does the root template contain everything that needed to be created ? becasue i see that there are scripts but there are not used ?

**Comment by couchgott** [comment]
Hi, 

the scripts are placed at the bootstrap S3 bucket and loaded onto the instances within the bootstrap process. You'll find this at the bbbapp* templates in the UserData Section of the EC2 Instance resource. the UsedData does some prep work and then sideload an bootstrap script. the script then orchestrates the copy and variable handling of each needed script and service and finally installs BBB. 
it's a bit cascaded how the actual setup is done. 

Best,

David

**Comment by RedaElHajjaji** [comment]
Hey,
in the setup.sh script there is a typo in line 127, it should be $SCALELITEREGISTRY instead of $SCALEILITEREGISTRY
and thanks

**Comment by couchgott** [comment]
yes you're right. was a late commit :-D

**Comment by couchgott** [comment]
fixed at the last release
