### ISSUE TITLE
Unable to Start the Bigbluebutton Meeting

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#13]
When i take the latest pull of the main branch and deploy it to the AWS and run the CLoudformation script -> The Deployment process succeded and greenlight is opening up.

The issue is when i go to start the meeting through greenlight, Following error comes up "Oops, there was an error when starting the meeting!"

**Comment by vsinghal339** [comment]
issue exists

**Comment by couchgott** [comment]
@vsinghal339 

can you check the big blue button and scalelite log entries (you'll find them in Cloudwatch Logs) for any errors. 
Also check the cloud-init-output.log of the turn and big blue button application instances.
Especially if the bootstraping went through. 

last but not least make sure the DNS entries of the application instances are added appropriately to Route53 and you can resolve the names from your devices. 

hope that helps

**Comment by couchgott** [comment]
closing due inactivity
