### ISSUE TITLE
General Query

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#14]
Let's Assume:
1. We have following configuration for BBBAppStack Auto scaling group - 4(max server), 1 (desired server) and 1 (min server). 
2. We have 100 users who will use this whole architecture for web conferencing meetings
3. One server on BBBAppStack can support only 10 users. After 10 users either it will crash or stop responding to new requests.
4. We have the policy for BBBAppStack to autoscale only if cpu is above 30%.

Scenario :
1. At particular time 10 users(teachers), through greenlight, created meetings. In that case greenlight forward request to scalelite and in turn scalelite will make 10 session in 1 server of BBBAppstack which is the only server at the moment is running. So now only 1 server in BBBAppstack knows about 10 users meeting info.

2. After creating meeting, these 10 teachers asks their individual 1 student each to join the meeting. So total of we have 20 users (10 teachers and 10 students) ready to join the meeting.

Question:
1. If these 10 students join the meeting either at the same time or one after another in some small interval, Does in that case autoscaling will work or make any sense? Because all these 20 users will be redirected to server 1 of BBBAppStack and it has the capacity of only 10 users. 

2. Although, let's say when 10 teachers created a meeting and CPU goes to 40% and BBBAppStack now have 2nd server as a part of autoscaling. Now the server 1 will crash as none of the user is redirected to server 2 because all of the session is made in server 1 by scalelite.

**Comment by couchgott** [comment]
Hey vsinghal, 

for 100 Users a single node setup should be enough if you rightsize the application server. According to the BBB [documentation](https://docs.bigbluebutton.org/2.2/install.html) a c5.2xlarge should be good up until round about 250 Users in a single meeting. 
You can have scale-out  via CPU targets. But i highly recommend to prevent the ASG to scale-in when CPU is low. As mentioned at the post, the ASG does not know if a meeting is running on an instance by default. A meeting with 2 People might not have any significant CPU load. this might cause in running meetings to be terminated (and the users need to reconnect/restart the meeting) 

to your questions: 

1: all users of a meeting will end up at the same BBB instance. a meeting is just "existing" on one instance and scalelite will make sure all users end up at the right one. So, you need to size the instances according to the maximum number of users you expect in one meeting. Different meetings will be dristributed to other bbb instances based on scalelites instance load and users information it gets from the bbb instances. 

2. if an instance is shutdown or terminated the instance will get removed from scalelite (with the scalelite handler sysdtemD sceript we added to the instances) if the instance is crashed scalelite will recordnize it with a delay and redirects the meeting to another, running instance. 

does this answers your questiong? :)

**Comment by vsinghal339** [comment]
The answer seems good. We have 3000 users and sometimes only 250 users use our platform, sometimes 1000 and sometimes all 3000 use it. If i configure BBBAppStack to have minimum 2 servers and maximum 20 servers, Does this architecture will support 3000 users if they comes immediately at the same time

**Comment by couchgott** [comment]
i would say in theory it should support this amount of users. but i haven't tested it. i read somewhere in the BBB forums (sry i do not have any link) that roundabout 500 users in a single meeting is the maximum you can get due limitations of the node.js within the big blue button deployment. 
multiple meetings will distribute over multiple instances, so no issue here. 

to have a real automatic scale i would recommend to extend the code and add a lambda function checking server load and meetings on the instances and use this function to get triggers for scale-out and in. like "load over 5, scale out" and "load below 1 and active meetings = 0, terminate instance and scale in" kind of logic. alternatively change the ASG config to only scale-out on load/cpu and scale in only via lambda, scheduled and checking if meetings are on the instance regulary. 

as said, it's a higher effort to have autoscaling at the bbb instances. 

the turn server should handle the amount, maybe you need to scale vertically and choose a larger instance here. maybe an m5a.large to get more consistent performance if you have continuous high load. 

scaling the turn server for HA or Load Balancing is a different kind of story tough. but i think for 3000 users its not needed. (but again, i did not test with 3000 users ;)  )
