### ISSUE TITLE
add some customization hints to the readme.md

### ISSUE THREAD

**Issue by couchgott** [aws-samples/aws-scalable-big-blue-button-example#22]
**Is your feature request related to a problem? Please describe.**
Add some basic customization hints into the readme.md also where at the BBB documentation it is clarified and how to extend tasks (greenlight) or application instance customization. 

**Additional context**
Also clarify how updates will be processed via Amazon Cloudformation

**Comment by shadeimi** [comment]
Also add aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com

**Comment by couchgott** [comment]
solved with #39
