### ISSUE TITLE
I have a problem with AWS Scalable

### ISSUE THREAD

**Issue by smirelesry** [aws-samples/aws-scalable-big-blue-button-example#23]
**I executed this command:**

./setup.sh -p bbb-example -e contabilidad@example.com -h Z10230013GF1WELLRWCUI -s bbb-stack -d bbb.example.com

**then I get the following error:**

##################################################
##################################################
File Copy finished
Building the BBB Environment
##################################################
./setup.sh: line 110: jq: command not found

Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name bbb-stack
##################################################
Deployment finished

**I executed this command:**
aws cloudformation describe-stack-events --stack-name bbb-stack

**then I get the following error:**
But I don't see what is the mistake.

Please help me.

**Comment by couchgott** [comment]
Hi, 
Please make sure 'jq' is installedat the system you're starting the script from.

Cheers!

**Comment by smirelesry** [comment]
Thanks!! I have a new problem:


The following resource(s) failed to delete: [BBBECSCapacityProvider, BBBECSCluster].

![image](https://user-images.githubusercontent.com/33386476/94864881-47718600-0402-11eb-880c-01303d11a99c.png)

**Comment by gamferreira** [comment]
Hey, @smirelesry have you checked the 'Events' tab? There you might find the error message in more detailed.

**Comment by couchgott** [comment]
Hey @smirelesry when you try to delete again, do you get the option to skip some undeletable resources? if so you can skip them and manually delete those resources. 
additionally, what @gamferreira said. look at the events and check what exactly could not be deleted. 
feel free to share with us :) 

Cheers!
