### ISSUE TITLE
Route53 A entries not being deleted after BBB instance is terminated

### ISSUE THREAD

**Issue by gamferreira** [aws-samples/aws-scalable-big-blue-button-example#24]
**Describe the bug**
Hey guys! First of all congratulations on the awesome job! I am using your solution to host a BBB fleet and it is working quite well. I am planning to contribute to the project by adding some new features that I will be sharing in the next weeks.

For now, I noticed that after terminating some EC2 BBB instances, my route53 still contains the old/terminated entries. 

I do see the `ExecStop` for /usr/local/bin/route53-handler.sh but I think it is not always being called.

**To Reproduce**
1. Spin up new BBB instances from Autoscaling/EC2
2. Terminate them
3. Check Route53 entries. Some of the A entries remain there.

**Expected behavior**
DNS 'A' entry is deleted after EC2 termination.

**Screenshots**
![image](https://user-images.githubusercontent.com/884314/94968921-14aeb700-0502-11eb-8b3a-95b5169e8cb2.png)

Are you guys aware of this issue? 
Before trying to fix it I wanted to check with you. Otherwise, I can work on it and create a PR.

**Comment by couchgott** [comment]
Hey, 

it "should" work, At least it was tested. Did you forcefully terminate the instances? That could be a reason. 

Cheers!

**Comment by gamferreira** [comment]
No, they were terminated through ASG. I suspect the call to R53 is not fully completed when the instance terminates. Perhaps we could use ASG lifecycle hook to guarantee it is fully executed (just an idea).

**Comment by couchgott** [comment]
Hey, sounds like a reasonable idea. When testing the termination + route53 was reliable but it sounds very good to have another approach to ensure a clean environment which is more reliable.

**Comment by gamferreira** [comment]
@couchgott, cool - I will try to work on it this week and hopefully send you a pull request.

**Comment by couchgott** [comment]
Most likely Cloudwatch Events -> SNS -> Lambda Function to Cleanup. 
imho. would be a simple and reliable version

**Comment by couchgott** [comment]
This should be finally solved with Release 4.0.0
Added some additional code to the handler services for systemd seemed todo the trick for all "intentional" terminations, reboots, stops of instances. 
only thing "left" would be that a crashing instance would not be able to remove it's entires. 

same for the handling of entires from scalelite.
