### ISSUE TITLE
bbb-stack-BBBTurnStack fails

### ISSUE THREAD

**Issue by niks913** [aws-samples/aws-scalable-big-blue-button-example#25]
The AutoScaling group creation in the bbb-stack-BBBTurnStack waits for the success signal from EC2 and it does not receive any. As a result the stack creation fails.
I have tried this in the eu-west-1 and eu-west-2 regions.

![image](https://user-images.githubusercontent.com/40640125/95613946-5819a000-0a83-11eb-845a-291fcd8e82ba.png)

**Comment by couchgott** [comment]
Hey @niks913 can you check if #1 does also apply to your issue (troubleshooting hints are at this ticket)

**Comment by couchgott** [comment]
closing due inactivity
