### ISSUE TITLE
BBBTurnAutoScaling: CREATE_FAILED

### ISSUE THREAD

**Issue by SusantaNeelamani** [aws-samples/aws-scalable-big-blue-button-example#26]
**Describe the bug**
BBBTurnAutoScaling : CREATE_FAILED : Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**To Reproduce**
1. Followed the steps with the following command
./setup.sh -p default -e susantaxx@example.com -h Z3J5XNDXTFOEVY -s bbb-stack -d bigbluebutton.xxxxx.de

Cloud formation failed with the following error.

BBBTurnAutoScaling	
CREATE_FAILED	Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Expected behavior**
Cloud Formation should finish successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/43719649/96355306-6e0d0d80-10e0-11eb-9b45-55897ad9089e.png)

**Comment by couchgott** [comment]
Hey @SusantaNeelamani can you check if #1 does also apply to your issue (troubleshooting hints are at this ticket)

**Comment by couchgott** [comment]
closing due inactivity
