### ISSUE TITLE
Changing Branding logo doesn't work

### ISSUE THREAD

**Issue by Corradones** [aws-samples/aws-scalable-big-blue-button-example#27]
Hi all,
when in Greenlight (as administrator) i try to change the brand image, i insert the new image link , press on change image button and a banner on the top tell me that the image it's now changed. But the image address in text box become back the older one , and the image is not really changed.

**To Reproduce**
Just try straightly to change logo in greenlight

**Expected behavior**
Change logo

![Schermata a 2020-10-22 13-18-37](https://user-images.githubusercontent.com/72140228/96864802-46fc6600-1469-11eb-8060-52cd848a1236.png)

PS. i can change regularly color, user and any other settings. And the platform works great for all the rest (really a cool solution!)

Thank s for any suggests.

**Comment by Corradones** [comment]
Problem solved. Just rebuilt the docker image of greenlight.

1) cp "sample.env" in ".env" 
2)docker-compose  down
3)docker-compose  up -d

**Comment by tetrex** [comment]
how do you do that 
i.e i cannot find the docker image when i log in from session manager
