### ISSUE TITLE
Code deployment and autoscaling questions.

### ISSUE THREAD

**Issue by serveradmin247** [aws-samples/aws-scalable-big-blue-button-example#3]
It's not a bug. But a few questions

Once we deploy the application if we want to make any changes to the code ( theme, or some other customization), how can we deploy it to this stack?

We are already using a single server model and I know developers ( I am not a developer) customized a lot that.

Also, it's said that the auto-scaling will not work dynamically and we need to set the desired numbers manually. Is it correct? Once we change the Maximum number, is there an image to start the new instance automatically?

**Comment by couchgott** [comment]
Hi ,

you can make any changes you want. I would recommand to add customizations to the UserData at the instance bootstrab though to keep it redeployable and easy to maintain. 

yes the scaling of the application servers at the current state is kind of "planned/manually" as pointed out at the docu. The Autoscaler is not capable to "know" if an instance is used for a meeting or not. For instance having dynamic scale-in might cause the ASG terminate an instance with a small meeting as it might run under the cpu minimum usage . 

Cheers!
