### ISSUE TITLE
How does aws-scalable-big-blue-button-example WORKS ?  (Info request, not ISSUE)

### ISSUE THREAD

**Issue by Corradones** [aws-samples/aws-scalable-big-blue-button-example#30]
Hi All,
after some days of studying of this really interesting AWS scalable system I think i need some clarification of working flow. Several things are not so clear to me.
Can you please solve my doubts? I hope to be able to put questions as shortly and direct as possible.

PREMISE: my system is installed and perfectly working.What I don't have clear is the role of any kind of instance in the system.

After a check my results are:
bbbAPPstack  ---> runs just a simple BBB installation (no other software, no dockers, no greenlight, no scalelite)
bbbTURNstack ----> runs TURN server and a small docker with AMAZON AGENT

bbbECSstack -----> EACH INSTANCE OF THIS KIND RUNS A DIFFERENT SOFTWARE eg:
**First instance** runs Scalelite docker containers (and amazon agent)     NB: NO BBB on this instance
**Second instance** runs Greenlight docker container (and amazon agent)    NB: NO BBB on this instance
**All the other following instance** of bbbECSstack....... doesn't run any software (???), only AmazonAMI OS  (?!?)

And now the questions:

- What is the function of the third to number-n remaining bbbECSstack instances if no software is installed on?

- Why the auto scaling scales up and down the bbbECSstack instances instead of bbbAPPstack instances? Don't should scale the BBB number?

- What is the instance type that need the more cpu power? I mean The working units that must be scaled.
Suppose i have 1000 users on the system, which number of each instances i can expect in my ec2? (approximately)

- Why the bbbAPPstack and bbbTURNstack instances are inserted in autoscaling group too?
Why a turn server should scale?
Why the scaling rules of these is set to "1" (and the bbbECSstack scale from 4 to 10 instead)

Sorry for bothering but I'm really confused.

I expected to have:

number N bbbAPPstack instances on scaling group (in the standard conf value is from 4 to 10) which distribute and process the cpu load of the session in BBB.
number 1 permanent Turn Server (no autoscaling group)
number 1 permanent server running Scalelite containers (no autoscaling group)
number 1 permanent server runnin Greenlight container (but the last two server could run in one unique server at all)  (no autoscaling group)

Really thanks for enlightenments that i think could be useful for other people too. (in readme file is not specified all this)

Corrado

**Comment by couchgott** [comment]
Hey @Corradones 

some answeres: 

> What is the function of the third to number-n remaining bbbECSstack instances if no software is installed on?
A cluster usually does have a minimum of 3. You can alter the amount of ECS instances down to 2 if you like. It's basically a suggestion from our side. e.g. in the matter the Scalelite and/or Greenlight Applications need to scale they can spread over all 3 instances. 

>     Why the auto scaling scales up and down the bbbECSstack instances instead of bbbAPPstack instances? Don't should scale the BBB number?
There are 3 Autoscaling Groups for App Servers (planned scaling), turn servers (basically for HA) and ECS Instanes (automatically on-demand) 

>     What is the instance type that need the more cpu power? I mean The working units that must be scaled.
with high usage towards user per meeting the Application Servder instances will cover most of the workloads afaik,. 

>     Suppose i have 1000 users on the system, which number of each instances i can expect in my ec2? (approximately)
This is related to 2 factors. Concurrent users per meeting. meetings conncurrency (how many meetings same time) 
from the BBB documenatation c5.xlarge are recommend. usually these instances can take up to 250/300 users at a single meeting. 
Scaling with multible instances will help you to run multible meetings whith the meeting concurrency. larger instances will help with larger meetings with more users in a single meeting. 
The meetings are distributed over multible instances. but one meeting will always be redirected to a single instance. 

> 
    Why the bbbAPPstack and bbbTURNstack instances are inserted in autoscaling group too?
the app stack as described above. The turn servers for HA mostly as at the current state there would be no traffic destribution. This can be extended adding a coturn cluster config to the setup. which we did not do for the sample. (ref. to the coturn documentation for more info how to approach this) 
Clustering coturn would not be something you need for "just" 1K of users imho though. 

> 
    Why a turn server should scale?s
 see above. 

>    Why the scaling rules of these is set to "1" (and the bbbECSstack scale from 4 to 10 instead)
just examples. alter/adjust to your own needs ;)

**Comment by couchgott** [comment]
closing due inactivity

**Comment by Corradones** [comment]
Sorry Dave for my late due to workload in these days, and thanks for your precious explanation.
A this point i think i misunderstood some details:
 BBBApp scaling is not based on capacity providing? In which case BBBAPP scale in /out?  What do you mean with planned scaling? In self dimensioning of BBBApp autoscaling group i don't find any activation event (differently from BBBECS group).
Sorry for bother, thanks a lot

PS.
is there a rollback scripts somewhere? I have had a lot of try and i'd like to destroy all the previous deploys, but going to every AWS service section to delete stuff is a pain!

**Comment by couchgott** [comment]
Hi @Corradones,

you're right. the app servers do not have any Capacity Planning/triggers added/enabled.
This is caused by what i tried to clarify above or at the documentation. 
At the current state of the code/deployment we do not know if a BBB application instance is empty or just a small meeting going on. so we cannot scale-in automatically w/o possible dropping an ongoing meeting. 

This is what i'll  try to address with #40 when i find time. 

the "rollback" script is called "destroy.sh" you'll find it in the root of the project. 
if you deleted the cloudformation stacks manually you also should be good, everything deployed should be removed when they got deleted successfully.

**Comment by Corradones** [comment]
clear. Thanks again. All this is really engaging  :-)
