### ISSUE TITLE
The following resource(s) failed to create: [BBBTurnAutoScaling].

### ISSUE THREAD

**Issue by fla243** [aws-samples/aws-scalable-big-blue-button-example#32]
**Describe the bug**
Embedded stack arn:aws:cloudformation:eu-central-1:008558560860:stack/bbb-stack-BBBTurnStack-88R9Q16QW501/3bee7e60-182e-11eb-837b-0a7e60142948 was not successfully created: The following resource(s) failed to create: [BBBTurnAutoScaling].

I do all the thing concerning sub domain. When I do a traceroute on the subdomain I correctly see AWS dns.
Here is the output of the  /var/log/cloud-init-output.log on Turn session:

`2020-10-27 08:31:47 (11.5 MB/s) - ‘/usr/local/bin/cli53’ saved [19566592/19566592]

+ sudo chmod +x /usr/local/bin/cli53
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1pftq9qh8838r/route53-handler.service /etc/systemd/system/route53-handler.service
download: s3://bbb-stack-sources-bbbstackbucket-1pftq9qh8838r/route53-handler.service to etc/systemd/system/route53-handler.service
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1pftq9qh8838r/route53-handler.sh /usr/local/bin/route53-handler.sh
download: s3://bbb-stack-sources-bbbstackbucket-1pftq9qh8838r/route53-handler.sh to usr/local/bin/route53-handler.sh
+ chmod +x /usr/local/bin/route53-handler.sh
+ sed -i s/INSTANCE_PLACEHOLDER/tu-km6ipl/g /etc/systemd/system/route53-handler.service
+ sed -i s/ZONE_PLACEHOLDER/Z07875661V6OW2AUJ867U/g /etc/systemd/system/route53-handler.service
+ systemctl daemon-reload
+ systemctl enable route53-handler
Created symlink /etc/systemd/system/multi-user.target.wants/route53-handler.service → /etc/systemd/system/route53-handler.service.
+ systemctl start route53-handler
Job for route53-handler.service failed because the control process exited with error code.
See "systemctl status route53-handler.service" and "journalctl -xe" for details.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:final' at Tue, 27 Oct 2020 08:30:38 +0000. Up 24.06 seconds.
2020-10-27 08:31:51,024 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-10-27 08:31:51,025 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 finished at Tue, 27 Oct 2020 08:31:51 +0000. Datasource DataSourceEc2Local.  Up 95.30 seconds
$ systemctl status route53-handler.service
● route53-handler.service - Run Route53 Handling at Start and Stop
   Loaded: loaded (/etc/systemd/system/route53-handler.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-10-27 08:31:51 UTC; 9min ago
  Process: 8219 ExecStart=/usr/local/bin/route53-handler.sh -h tu-km6ipl -m create -z Z07875661V6OW2AUJ867U (code=exited, status=203/EXEC)
 Main PID: 8219 (code=exited, status=203/EXEC)`

**Comment by couchgott** [comment]
hi @fla243,

can you log into the instance and post the output of "journalctl -xe" to get more details out of the service error. 

Thanks!

**Comment by fla243** [comment]
$ journalctl -xe
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.

**Comment by couchgott** [comment]
do not forget the sudo ;)

**Comment by fla243** [comment]
Sorry

Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
$ sudo journalctl -xe
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: Job for route53-handler.service failed because the control process exited with error code.
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: See "systemctl status route53-handler.service" and "journalctl -xe" for details.
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:final' at Tue, 27 Oct 2020 09:17:34 +0000. Up 25.11 seconds.
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: 2020-10-27 09:18:51,437 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: 2020-10-27 09:18:51,439 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]:
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: #############################################################
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: -----BEGIN SSH HOST KEY FINGERPRINTS-----
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: 1024 SHA256:31SebSWsvBEkNRbnx/rh6BunN6Eb06wO2v0nyHZvtm8 root@ip-10-1-17-34 (DSA)
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: 256 SHA256:PP3j/PygH8RqU0k5VjAcxGeFYYu3bKMAysYgEa8RvyM root@ip-10-1-17-34 (ECDSA)
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: 256 SHA256:vwZzZKBO4JDOPpdETsKGiCnN1GUQSXzBhqplDaVwMFE root@ip-10-1-17-34 (ED25519)
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: 2048 SHA256:THPy9DlZftbNlQrpBaeUofXvHZV6pFLOb7F8MTHYGW0 root@ip-10-1-17-34 (RSA)
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: -----END SSH HOST KEY FINGERPRINTS-----
Oct 27 09:18:51 ip-10-1-17-34 ec2[8178]: #############################################################
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Oct 27 09:18:51 ip-10-1-17-34 cloud-init[1758]: Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 finished at Tue, 27 Oct 2020 09:18:51 +0000. Datasource DataSourceEc2Local.  Up 101.20 seconds
Oct 27 09:18:51 ip-10-1-17-34 systemd[1]: cloud-final.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 09:18:51 ip-10-1-17-34 systemd[1]: cloud-final.service: Failed with result 'exit-code'.
Oct 27 09:18:51 ip-10-1-17-34 systemd[1]: Failed to start Execute cloud user/final scripts.
-- Subject: Unit cloud-final.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit cloud-final.service has failed.
--
-- The result is RESULT.
Oct 27 09:18:51 ip-10-1-17-34 systemd[1]: Reached target Cloud-init target.
-- Subject: Unit cloud-init.target has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit cloud-init.target has finished starting up.
--
-- The start-up result is RESULT.
Oct 27 09:18:51 ip-10-1-17-34 systemd[1]: Startup finished in 6.144s (kernel) + 1min 35.138s (userspace) = 1min 41.283s.
-- Subject: System start-up is now complete
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- All system services necessary queued for starting at boot have been
-- started. Note that this does not mean that the machine is now idle as services
-- might still be busy with completing start-up.
--
-- Kernel start-up required 6144992 microseconds.
--
-- Initial RAM disk start-up required INITRD_USEC microseconds.
--
-- Userspace start-up required 95138258 microseconds.
Oct 27 09:22:45 ip-10-1-17-34 amazon-ssm-agent.amazon-ssm-agent[1625]: 2020-10-27 09:22:45 INFO [HealthCheck] HealthCheck reporting agent health.
Oct 27 09:23:31 ip-10-1-17-34 sudo[8212]: ssm-user : TTY=pts/0 ; PWD=/var/snap/amazon-ssm-agent/2012 ; USER=root ; COMMAND=/bin/journalctl -xe
Oct 27 09:23:31 ip-10-1-17-34 sudo[8212]: pam_unix(sudo:session): session opened for user root by (uid=0)

**Comment by couchgott** [comment]
can you take a look at the systemd service. there is a command/script included for the start you also can run manually. (just be sure to set the parameters for the script) then run it ad-hoc and look for any error message popping up.

**Comment by fla243** [comment]
It is this command?
/usr/local/bin/cli53 rrcreate --replace Z07875661V6OW2AUJ867U "tu-puivjp 60 A 18.193.127.24"
Because I run it successfully on the instance

**Comment by couchgott** [comment]
yes i know. you could prevent this .. if you look into the userData of the instance there is a cfn-signal command. if you send this manually the stack will deploy successfully so you can keep the instance deployed. 
i could not reproduce the error on my side yet. so we need to work on your instance to debug, sry.

**Comment by couchgott** [comment]
apart from that we need to find the issue why the service does not start on your instance while the command does. will dig into it.

**Comment by fla243** [comment]
What should I do?
Launch the command /usr/local/bin/route53-handler.sh -h INSTANCE_PLACEHOLDER -m create -z ZONE_PLACEHOLDER

**Comment by fla243** [comment]
In fact when I try to launch 
/usr/local/bin/route53-handler.sh -h tu-uxm5nu -m create -z Z07875661V6OW2AUJ867U
sh: 7: /usr/local/bin/route53-handler.sh: not found

**Comment by couchgott** [comment]
can you check if it exist at the source s3 bucket? Also if you find an error message at the cloud-inits s3 copy commands?

**Comment by fla243** [comment]
I have this error
+ sudo chmod +x /usr/local/bin/cli53
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1rufp9bvrqvu3/route53-handler.service /etc/systemd/system/route53-handler.service
download: s3://bbb-stack-sources-bbbstackbucket-1rufp9bvrqvu3/route53-handler.service to etc/systemd/system/route53-handler.service
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1hverft55knav/route53-handler.sh /usr/local/bin/route53-handler.sh
fatal error: An error occurred (404) when calling the HeadObject operation: Key "route53-handler.sh" does not exist
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:final' at Tue, 27 Oct 2020 12:18:16 +0000. Up 32.69 seconds.
2020-10-27 12:19:33,573 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-10-27 12:19:33,574 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 finished at Tue, 27 Oct 2020 12:19:33 +0000. Datasource DataSourceEc2Local.  Up 109.94 seconds

**Comment by couchgott** [comment]
did you check if the S3 bucket has been created (the bootstrapping S3 Bucket) and the setup.sh script copied over the script files. 
If you did not use setup.sh .. please make sure you copied over the content of ./scripts to the S3 bucket before starting the deplyoment.

**Comment by fla243** [comment]
I use the setup script.
I have this bucket
![bucket](https://user-images.githubusercontent.com/16593311/97304009-73debd80-185b-11eb-8722-9b795a0ce1ac.png)

**Comment by couchgott** [comment]
if you use the copy bit  wherfrom the userdata manually, does it work? 

          # create script for route53-handler
          aws s3 cp s3://${BBBStackBucketStack}/route53-handler.service /etc/systemd/system/route53-handler.service
          aws s3 cp s3://${BBBStackBucketStack}/route53-handler.sh /usr/local/bin/route53-handler.sh
          chmod +x /usr/local/bin/route53-handler.sh

**Comment by fla243** [comment]
Following the stacktrace, file is correctly copied from s3

2020-10-27 12:57:26 (11.6 MB/s) - ‘/usr/local/bin/cli53’ saved [19566592/19566592]

+ sudo chmod +x /usr/local/bin/cli53
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1s2r6yhouxjjo/route53-handler.service /etc/systemd/system/route53-handler.service
download: s3://bbb-stack-sources-bbbstackbucket-1s2r6yhouxjjo/route53-handler.service to etc/systemd/system/route53-handler.service
+ aws s3 cp s3://bbb-stack-sources-bbbstackbucket-1s2r6yhouxjjo/route53-handler.sh /usr/local/bin/route53-handler.sh
download: s3://bbb-stack-sources-bbbstackbucket-1s2r6yhouxjjo/route53-handler.sh to usr/local/bin/route53-handler.sh
+ chmod +x /usr/local/bin/route53-handler.sh
+ sed -i s/INSTANCE_PLACEHOLDER/tu-bawl75/g /etc/systemd/system/route53-handler.service
+ sed -i s/ZONE_PLACEHOLDER/Z07875661V6OW2AUJ867U/g /etc/systemd/system/route53-handler.service
+ systemctl daemon-reload
+ systemctl enable route53-handler
Created symlink /etc/systemd/system/multi-user.target.wants/route53-handler.service → /etc/systemd/system/route53-handler.service.
+ systemctl start route53-handler
Job for route53-handler.service failed because the control process exited with error code.
See "systemctl status route53-handler.service" and "journalctl -xe" for details.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:final' at Tue, 27 Oct 2020 12:55:24 +0000. Up 28.11 seconds.
2020-10-27 12:57:29,945 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-10-27 12:57:29,945 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
ci-info: no authorized SSH keys fingerprints found for user ubuntu.
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 finished at Tue, 27 Oct 2020 12:57:30 +0000. Datasource DataSourceEc2Local.  Up 153.33 seconds

But when I try to launch the script I have a error.
See screenshot
![route53](https://user-images.githubusercontent.com/16593311/97305828-e6509d00-185d-11eb-924c-9db5c9e583fc.png)

**Comment by fla243** [comment]
For information when I return a cfn-singnal to success. It fails in the frontendAppsStack.
I have the same error than https://github.com/aws-samples/aws-scalable-big-blue-button-example/issues/28

**Comment by couchgott** [comment]
can you also check if the cli53 command is available?

**Comment by fla243** [comment]
Yes because I was able to run this command successfully
/usr/local/bin/cli53 rrcreate --replace Z07875661V6OW2AUJ867U "tu-puivjp 60 A 18.193.127.24"

**Comment by couchgott** [comment]
i rebuild the stack on my side from scratch. wile able to fix the secrets error from #28 i was not able to reproduce the route handler issue in any way. can you deploy from scratch (inluding to delete the source buckets) to have a clean try.

**Comment by fla243** [comment]
I always use de destroy.sh script before retry to launch a setup. Is it not enough?

**Comment by fla243** [comment]
I found the solution. I had to convert sh script to unix using dos2unix tool before launching the setup again.
But now I have this error:

Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for tu-ts2a92.bbb.cdmtest.site
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. tu-ts2a92.bbb.cdmtest.site (http-01): urn:ietf:params:acme:error:dns :: During secondary validation: DNS problem: query timed out looking up A for tu-ts2a92.bbb.cdmtest.site
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: tu-ts2a92.bbb.cdmtest.site
   Type:   None
   Detail: During secondary validation: DNS problem: query timed out
   looking up A for tu-ts2a92.bbb.cdmtest.site
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
bbb-install: Let's Encrypt SSL request for tu-ts2a92.bbb.cdmtest.site did not succeed - exiting
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:final' at Wed, 28 Oct 2020 07:57:28 +0000. Up 24.32 seconds.
2020-10-28 08:00:50,782 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-10-28 08:00:50,782 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed

**Comment by couchgott** [comment]
oh okay .. thats weird.

**Comment by fla243** [comment]
Do you have a idea for this DNS error?
Should I be able to have a webpage if I put the domain on a browser?

**Comment by couchgott** [comment]
try again from the instance with the /var/lib/cloud/instance/scripts/part-001 script maybe it's dns delay related

**Comment by couchgott** [comment]
i tried nslookup from my side and the dns query works for the server afaik

**Comment by fla243** [comment]
It loops over the 
host tu-gqclav.bbb.cdmtest.site
grep -m 1 'has address 18.157.180.216'
sleep 5
