### ISSUE TITLE
BBBNetworkStack-CREATE_FAILED - how to debug?

### ISSUE THREAD

**Issue by kevin-d-lee** [aws-samples/aws-scalable-big-blue-button-example#38]
Here is the appropriate log entry that caused the setup failure, but I couldn't glean enough info to track where the root cause exists.

{
            "StackId": "arn:aws:cloudformation:us-west-1:042922652305:stack/bbb1-stack/d66c2df0-1d5d-11eb-bee5-02e4b9b64ea3",
            "EventId": "BBBNetworkStack-CREATE_FAILED-2020-11-02T22:51:36.628Z",
            "StackName": "bbb1-stack",
            "LogicalResourceId": "BBBNetworkStack",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-1:042922652305:stack/bbb1-stack-BBBNetworkStack-LVS2AL80ZEQZ/e17afd70-1d5d-11eb-9f83-02d35d5fe6ed",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2020-11-02T22:51:36.628000+00:00",
            "ResourceStatus": "CREATE_FAILED",
            "ResourceStatusReason": "Embedded stack arn:aws:cloudformation:us-west-1:042922652305:stack/bbb1-stack-BBBNetworkStack-LVS2AL80ZEQZ/e17afd70-1d5d-11eb-9f83-02d35d5fe6ed was not successfully created: The following resource(s) failed to create: [BBBPrivateDBRouteTable3, BBBPrivateApplicationSubnet1, BBBPrivateDBSubnet3, BBBPrivateRouteTable1, BBBPrivateApplicationSubnet3, BBBIGWAttachment, BBBPrivateRouteTable2, BBBPublicApplicationSubnet3]. ",
            "ResourceProperties": "{\"TemplateURL\":\"https://s3.amazonaws.com/bbb1-stack-sources-bbbstackbucket-ak8g7jfhget1/bbb-on-aws-network.template.yaml\",\"Parameters\":{\"BBBVPCcidr\":\"10.1.0.0/16\",\"BBBPrivateDBSubnets\":\"10.1.9.0/24,10.1.10.0/24,10.1.11.0/24\",\"BBBEnvironmentName\":\"bbbonaws\",\"BBBEnvironmentStage\":\"dev\",\"BBBPublicApplicationSubnets\":\"10.1.15.0/24,10.1.16.0/24,10.1.17.0/24\",\"BBBEnvironmentType\":\"scalable\",\"BBBPrivateApplicationSubnets\":\"10.1.5.0/24,10.1.6.0/24,10.1.7.0/24\"},\"Tags\":[{\"Value\":\"BBBNetworkStack-bbbonaws\",\"Key\":\"Name\"},{\"Value\":\"bbbonaws\",\"Key\":\"Environment\"},{\"Value\":\"dev\",\"Key\":\"Stage\"}]}"
        },

**Comment by couchgott** [comment]
Hi @kevin-d-lee, 

there should be more content on the stack events. can you please look them up and post them here to get more insights. 

thanks! :)

**Comment by kevin-d-lee** [comment]
That was the first error in the log.  The rest of the entries prior to this one are CREATE_COMPLETE or CREATE_IN_PROGRESS.   
 The one entry after this one is a CREATE_FAILED with a "ResourceStatusReason": "Resource creation cancelled".  I assumed the failure caused this following one to cancel.  And the remainder of the entries are ROLLBACK_IN_PROGRESS and DELETE_IN_PROGRESS.  

That is why I'm having troubles debugging what the core issue is.  Do you want to see the whole log?

**Comment by kevin-d-lee** [comment]
[stack.log](https://github.com/aws-samples/aws-scalable-big-blue-button-example/files/5484022/stack.log)
Here is the whole log from the describe-stack-events command.

**Comment by couchgott** [comment]
You can pull the events of the failed nested stack for futher debugging -> https://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stack-events.html (alternatively this can be checked at the AWS console at the event tab of the nested stack)
this should give a better idea what's going wrong 
the nested stack name is bbb1-stack-BBBNetworkStack-LVS2AL80ZEQZ in your case.

**Comment by kevin-d-lee** [comment]
I ran the describe stack events and I attached the full output in the stack.log file attachment above.  There is nothing in the console that isn't in the describe-stack-events output and still doesn't explain why it failed.

**Comment by couchgott** [comment]
Hi, 

there are no detail events at the log. so we cannot debug that. 
please use the aws console and browse to the stack (nested stack, not the main stack!) to the events tab. there should be an entry for each resource cfn is deploying and if failed a detailed error message…) 
If the stack got deleted because of failures, please select "deleted" on the pull-down menu top left or next to the search bar of the cloudformation console page.

**Comment by kevin-d-lee** [comment]
Sorry I was being obtuse.  I found the following 3 errosr:
BBBPrivateDBSubnet3 | CREATE_FAILED | Template error: Fn::Select cannot select nonexistent value at index 2
BBBPrivateApplicationSubnet3 | CREATE_FAILED | Template error: Fn::Select cannot select nonexistent value at index 2
BBBPublicApplicationSubnet3 | CREATE_FAILED | Template error: Fn::Select cannot select nonexistent value at index 2

When I look at the ResourceProperties of BBBNetworkStack-CREATE_IN_PROGRESS-2020-11-02T22:51:01.142Z, I see:
BBBPrivateDBSubnets\":\"10.1.9.0/24,10.1.10.0/24,10.1.11.0/24\"
BBBPrivateApplicationSubnets\":\"10.1.5.0/24,10.1.6.0/24,10.1.7.0/24\"
BBBPublicApplicationSubnets\":\"10.1.15.0/24,10.1.16.0/24,10.1.17.0/24\"

Which all seem to have 3 cidrs (index 2).  Next debugging step?  Thanks so much for your help.

**Comment by couchgott** [comment]
pfew. nasty issue..
so it seem you use the default parameter settings here. 
might it be you used these cidr blocks already somewhere else at the same account/vpc? 
does the vpc itself gets created? 
I could not reproduce this error with my test accounts so far.

**Comment by couchgott** [comment]
can you export / send the foll log of the events of that stack? just to check what have been done successfully beforehand

**Comment by couchgott** [comment]
another question. which region did you try to deploy to?

**Comment by kevin-d-lee** [comment]
[networkstack.log](https://github.com/aws-samples/aws-scalable-big-blue-button-example/files/5497517/networkstack.log)

I'm deploying to us-west-1.  
I do see the VPC creation complete successfully in the log

{
            "StackId": "arn:aws:cloudformation:us-west-1:042922652305:stack/bbb2-stack-BBBNetworkStack-LBCIR2P7KEIK/f2fda570-1fab-11eb-bb3a-06afe48149e9",
            "EventId": "BBBVPC-CREATE_COMPLETE-2020-11-05T21:15:21.859Z",
            "StackName": "bbb2-stack-BBBNetworkStack-LBCIR2P7KEIK",
            "LogicalResourceId": "BBBVPC",
            "PhysicalResourceId": "vpc-0eaed1effd3eb48f2",
            "ResourceType": "AWS::EC2::VPC",
            "Timestamp": "2020-11-05T21:15:21.859000+00:00",
            "ResourceStatus": "CREATE_COMPLETE",
            "ResourceProperties": "{\"CidrBlock\":\"10.1.0.0/16\",\"EnableDnsSupport\":\"true\",\"EnableDnsHostnames\":\"true\"}"
        },

It gets deleted on the failure.  I only see a single VPC in my account, but the cidr is: 172.31.0.0/16

Thanks so much for your assistance!

**Comment by couchgott** [comment]
here we go. us-west-1 does have 2 AZs (not 3). 
this is why do get that error. 
pfew. i need to think about how to make the 3rd AZ/Subnet optional in a reasonable way. that might take some time to get this sorted out. 
you can try deleting everiting referencing the index 2 (subnet creation + routing + approx more) out of the CFN code. 
but i am at the very moment if there would be side-effects. 
or deploy to a min 3AZ region for the moment while testing until we get to a version including the <3AZ regions.

**Comment by kevin-d-lee** [comment]
Thanks for figuring this out!  I'll probably try us-west-2 which has 4 az's.
