### ISSUE TITLE
Greenlight unable to show the recordings list

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#4]
We have setup this architecture in AWS and everything is working as expected Except the recordings list. We are unable to see any recordings list in the greenlight frontend. 

1. When we joined into a session we start the recording and after 3-4 minutes stop the recording and end the meeting. After waiting for 30 minutes still we are unable to see any recordings

**Comment by bklein1** [comment]
Thank you for your creating this issue. I will deploy the current status of the repository and try to reproduce the error.

**Comment by bklein1** [comment]
I could reproduce the error in my environment and started investigating

**Comment by bklein1** [comment]
Pull Request containing the fix is created
