### ISSUE TITLE
Error downloading CFN-SES file

### ISSUE THREAD

**Issue by niks913** [aws-samples/aws-scalable-big-blue-button-example#42]
**Describe the bug**
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for binxio-public-eu-west-1/lambdas/cfn-ses-provider-0.6.4.zip. S3 Error Code: AccessDenied. 

**To Reproduce**
1. Initiate the automated stack provisioning using the setup.sh
2. bbb-stack-BBBSESProviderStack fails with above error code
3. Scroll down to events section to get more details

**Expected behavior**
Cloudformation stack bbb-stack-BBBSESProviderStack in active state

**Comment by couchgott** [comment]
i'll check
