### ISSUE TITLE
Error: Missing service linked role for ECS

### ISSUE THREAD

**Issue by kevin-d-lee** [aws-samples/aws-scalable-big-blue-button-example#44]
Default configuration install.

Error occurred because missing service linked role for ECS.

Problem was resolved by running command:
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com --profile <profile>

Maybe this should be included in the pre-requisites?

**Comment by couchgott** [comment]
yep. it's at the troubleshooting section of the readme.md. 
but you're right. it might be good to mention it earlier in the docs.
