### ISSUE TITLE
Turn server create failed

### ISSUE THREAD

**Issue by thiru3706** [aws-samples/aws-scalable-big-blue-button-example#45]
bbb_turn server creation failed.
The turn server stack stay's in create in progress and then gives me the error below and changes to creation failed, then the total stack goes to rollback and delete's the stack.
Have followed the automated script ./setup.sh to launch the stack.
have added the stack error screen shots, please give me suggestions.

![Screenshot from 2020-11-09 13-36-08](https://user-images.githubusercontent.com/58164052/98525995-3b999f00-229f-11eb-9582-e313bc29a58f.png)
![Screenshot from 2020-11-09 13-07-09](https://user-images.githubusercontent.com/58164052/98526307-9c28dc00-229f-11eb-9f58-9f98cc9b0dfa.png)

how to debug this error!!!

**Comment by couchgott** [comment]
Hi @thiru3706 

please take a look at the troubleshooting section of the readme. 
also #1 will have some hints what's wrong in your setup.

**Comment by thiru3706** [comment]
thank you @couchgott  
have resolved that turn server issue i have a domain created in aws route53 within the same account as bigbluebuttontest.com and gave the fdqn as test.bigbluebuttontest.com and it filed to create when i put my fdqn as bigbluebuttontest.com it worked and installed but the BBB Demo is launched and in different fdqn the stack creates different fdqn as in the screen shot how could i install the BBB server and log in to it as admin.
![Screenshot from 2020-11-10 12-30-13](https://user-images.githubusercontent.com/58164052/98641159-56c4e700-2351-11eb-82de-94e21af1ddbf.png)
![Screenshot from 2020-11-10 12-30-19](https://user-images.githubusercontent.com/58164052/98641167-59274100-2351-11eb-94ec-58fdd6205795.png)
![Screenshot from 2020-11-10 12-30-22](https://user-images.githubusercontent.com/58164052/98641173-5a586e00-2351-11eb-96f9-71104b496416.png)
![Screenshot from 2020-11-10 12-30-39](https://user-images.githubusercontent.com/58164052/98641176-5b899b00-2351-11eb-8cc3-df69e8011519.png)
![Screenshot from 2020-11-10 12-30-50](https://user-images.githubusercontent.com/58164052/98641183-5cbac800-2351-11eb-84d8-c1aad4a9d42c.png)
![Screenshot from 2020-11-10 12-30-59](https://user-images.githubusercontent.com/58164052/98641186-5d535e80-2351-11eb-97a8-ae2b9c8a9efe.png)

expect with running BBB server full kit other than the demo.

**Comment by thiru3706** [comment]
The turn server error is resolved
