### ISSUE TITLE
Can't login to the green light page 

### ISSUE THREAD

**Issue by thiru3706** [aws-samples/aws-scalable-big-blue-button-example#46]
Can't login to the green light page.
as i have an error that i posted yesterday on turn server failure, i have used FDQN that BBB is to be installed instead of the domain, once i gave my domain the setup script the stack is created successfully and then the stack creates new records with two A records one for the turn server and other one for the Application server. while using the application's A record it redirects to the Demo page, i need to go to the green light page to access the BBB server.

The solution I like
i am looking for the green light login page.

Alternatives I considered
here it is demo server, is there any way to change the demo to production without changing the entire stack.

**Comment by couchgott** [comment]
the Frontend should listen at: conference.the.domain.tld 
check if nslookup gives you an entry first. 
Cheers!

**Comment by thiru3706** [comment]
Thanks @couchgott 
thank you for your help and assistance have successfully installed and launched the BBB server

Thanks and regards
