### ISSUE TITLE
1002: Could not make a WebSocket connection

### ISSUE THREAD

**Issue by parrajeremy** [aws-samples/aws-scalable-big-blue-button-example#49]
Setup on a subdomain 

1. Conference starts fine
2. Cannot connect microphone - from documentation this is a FreeSwitch issue https://docs.bigbluebutton.org/2.2/configure-firewall.html#ec2
3. Camera joins fine

$ systemctl status freeswitch
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-11-25 00:34:50 UTC; 3h 12min ago
 Main PID: 16506 (freeswitch)
    Tasks: 37
   Memory: 38.2M
      CPU: 1min 33.928s
   CGroup: /system.slice/freeswitch.service
           └─16506 /opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait -nonat

**Comment by parrajeremy** [comment]
solved following 
https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-a-dummy-nic-if-required

manually configured "Dummy Nic" and modified /opt/freeswitch/conf/sip_profiles/external.xml

Still need to work this into Iac scripts

**Comment by parrajeremy** [comment]
@couchgott  I can amend above with the root of this seems to be getting the value for EXTERNAL_IP_ADDRESS set correctly so that freeswitch can operate behind ec2 security group. At this point I have successfully changed individual EC2 instance, but of course that doesn't fix the issue at the top level.

**Comment by couchgott** [comment]
Hmmm i did not come accross that issue when testing. When bootstrapping the External IP get's set for freeswitch the right way. Also Security groups do not do any NAT at AWS. They're working at the ENI of each instance so they do use the external IP of the EC2 instance and are fully transparent for the applications on it. 
Can you try to terminate the EC2 instance and let the ASG redeploy. Afterwards check the /var/log/cloud-init-output.log, there you should find the freeswitch external IP used.

**Comment by parrajeremy** [comment]
$ grep external /var/log/cloud-init-output.log
                   external_rtp_ip: 34.213.104.147
                   external_sip_ip: 34.213.104.147
/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}

which matches the ec2 instance 

new instance still gives 1002 error.

Looking through BBB documentation now and will post back with any findings

**Comment by parrajeremy** [comment]
Additional info: My domain is primarily hosted on GCP. My DNS record there is set up with NS records for my hosted zone on AWS (a subdomain).

**Comment by couchgott** [comment]
can you check if that IP has been set for "wss-binding" within the external.xml config of freeswitch?

**Comment by parrajeremy** [comment]
it has not 
$ grep wss-binding /opt/freeswitch/conf/sip_profiles/external.xml
    <param name="wss-binding" value=":7443"/>

**Comment by couchgott** [comment]
what is the reply you get when running 
curl --trace-ascii - -k https://EXTERNAL-IP-ADDRESS:443/bigbluebutton/api
on the server?

**Comment by parrajeremy** [comment]
in vars.xml we have
  <X-PRE-PROCESS cmd="set" data="external_rtp_ip=34.213.104.147"/>
  <X-PRE-PROCESS cmd="set" data="external_sip_ip=34.213.104.147"/>

**Comment by parrajeremy** [comment]
curl --trace-ascii - -k https://EXTERNAL-IP-ADDRESS:443/bigbluebutton/api

-> success

 curl --trace-ascii - -k https://EXTERNAL-IP-ADDRESS:443/bigbluebutton/api
== Info: Could not resolve host: EXTERNAL-IP-ADDRESS
== Info: Closing connection 0
curl: (6) Could not resolve host: EXTERNAL-IP-ADDRESS
$ curl --trace-ascii - -k https://34.213.104.147:443/bigbluebutton/api
== Info:   Trying 34.213.104.147...
== Info: Connected to 34.213.104.147 (34.213.104.147) port 443 (#0)
== Info: found 138 certificates in /etc/ssl/certs/ca-certificates.crt
== Info: found 552 certificates in /etc/ssl/certs
== Info: ALPN, offering http/1.1
== Info: SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
== Info:         server certificate verification SKIPPED
== Info:         server certificate status verification SKIPPED
== Info:         common name: vc-0spkrt.conference-test.savvyreading.com (does not match '34.213.104.147')
== Info:         server certificate expiration date OK
== Info:         server certificate activation date OK
== Info:         certificate public key: RSA
== Info:         certificate version: #3
== Info:         subject: CN=vc-0spkrt.conference-test.savvyreading.com
== Info:         start date: Wed, 25 Nov 2020 17:25:50 GMT
== Info:         expire date: Tue, 23 Feb 2021 17:25:50 GMT
== Info:         issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
== Info:         compression: NULL
== Info: ALPN, server accepted to use http/1.1
=> Send header, 95 bytes (0x5f)
0000: GET /bigbluebutton/api HTTP/1.1
0021: Host: 34.213.104.147
0037: User-Agent: curl/7.47.0
0050: Accept: */*
005d:
<= Recv header, 15 bytes (0xf)
0000: HTTP/1.1 200
<= Recv header, 15 bytes (0xf)
0000: Server: nginx
<= Recv header, 37 bytes (0x25)
0000: Date: Wed, 25 Nov 2020 18:55:51 GMT
<= Recv header, 38 bytes (0x26)
0000: Content-Type: text/xml;charset=utf-8
<= Recv header, 28 bytes (0x1c)
0000: Transfer-Encoding: chunked
<= Recv header, 24 bytes (0x18)
0000: Connection: keep-alive
<= Recv header, 52 bytes (0x34)
0000: X-Application-Context: application:production:8090
<= Recv header, 25 bytes (0x19)
0000: Cache-Control: no-cache
<= Recv header, 35 bytes (0x23)
0000: P3P: CP="No P3P policy available"
<= Recv header, 2 bytes (0x2)
0000:
<= Recv data, 92 bytes (0x5c)
0000: 51
0004: <response>
0010: <returncode>SUCCESS</returncode>
0032: <version>2.0</version>
004a: </response>
0057: 0
005a:
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>== Info: Connection #0 to host 34.213.104.147 left intact

**Comment by couchgott** [comment]
seems like the error is not caused directly by a broken Freeswitch deployment.

Also, when i browse to: https://34.213.104.147/bigbluebutton/api i get a success back. 
i am concerned the missing wss-binding though. 

what happens if you add this to the external.xml

<param name="wss-binding"  value="EXTERNAL_IP_ADDRESS:7443"/>

**Comment by parrajeremy** [comment]
That was my original fix, i.e. 1002 goes away. Of course this is not a sustainable fix. 

(I am setting up a new domain hosted solely in AWS to try an isolate the issue..will post back results

**Comment by couchgott** [comment]
i am currently redeploying the whole stack once again and keep an extra eye on that setting. could not reproduce the issue yet but will see if anything comes accross. 
 DNS Should  be not the issue (ok you never know) .. as the only DNS related is that the CNAME gets into Route53 for Let's encrypt to get a valid SSL Cert (which worked on your setup). I happily share a test instance for a short test please ping me via email.

**Comment by couchgott** [comment]
i was able to reproduce. it seems the bbb-installer got an update breaking that part of the freeswitch config (i got an empty wss-binding entry to the external config) 
this used to work perfectly. give me some time to put an work-around into the bootstraping.

**Comment by couchgott** [comment]
checked and here we see the root of the issue: https://github.com/bigbluebutton/bbb-install/commit/5c6a738b8361a05b91554c897425c3c01bb4b180

**Comment by couchgott** [comment]
as it seems this comes from the bbb-installer i opened an issue with them: https://github.com/bigbluebutton/bbb-install/issues/306

**Comment by couchgott** [comment]
this should have been solved by the latest bbb-install.sh commit/version. can you please test again on your side?

**Comment by parrajeremy** [comment]
I am trying. I am running into what I expect is an unrelated issue, but was not an issue before

Embedded stack arn:aws:cloudformation:us-west-2:443096807045:stack/getsavvy-test-stack-BBBSESProviderStack-98AJ8L0G0B7H/34712550-35c2-11eb-ab31-068d06aa8c0d was not successfully created: The following resource(s) failed to create: [BBBSESProvider].

**Comment by couchgott** [comment]
if you look into the the stack (best via Console) you can look inro the detailed events. (the sub stack not the main stack events though)
please provide the error you'Re seeing there. it might be good to completely redeploy the stack after cleaning up using the destroy.sh

**Comment by couchgott** [comment]
closed due inactivity

**Comment by parrajeremy** [comment]
I apologize for the late response. I can confirm that the issue has been resolved.
