### ISSUE TITLE
Failing after BBBTurnAutoScaling: Resource creation Initiated 

### ISSUE THREAD

**Issue by georgethegreatat** [aws-samples/aws-scalable-big-blue-button-example#50]
**Describe the bug**

Hello. I'm stacked at the Turn server creation. I checked dns settings in route53, but all is working. 
After a server has been created I can not connect to it via SSH, but can do it via session manager. Seems like a some security group settings should be change. I'm using default settings to installation.

**Expected behavior**
Successfully installation.

**Screenshots**
![Image of Yaktocat](https://i.ibb.co/djFDR0H/save1.jpg)
![Image of Yaktocat](https://i.ibb.co/HDzsH0z/save2.jpg)

**Comment by couchgott** [comment]
Hi, 

while deploying (timout for the turn server is 15min) you can log into the instance via Systems Managers Session Managed. 
From there take a look into /var/log/cloud-init-output.log it give you some debug information where the bootstraping stops.

**Comment by georgethegreatat** [comment]
Hi @couchgott !

Thank you for fast reply.
Yes you're right, I'm already trying to some information there, please take a look.

![Image of Yaktocat](https://i.ibb.co/9ghMZqS/debug1.jpg)
&
![Image of Yaktocat](https://i.ibb.co/6rRmkHQ/debbug.jpg)

Also, as I said earlier,  I can not ping it from my instance and any ports is not available on the turn instance. 
What info I can put here to fast fix this bug ?

**Comment by georgethegreatat** [comment]
Dear @couchgott ,

You can close the ticket, there was a problem with DNS.
