### ISSUE TITLE
BBB-App-Stack Auto Scalig Policy

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#53]
I have deployed fresh setup and when i check the "BBBAppStack" under AutoScaling group,

1. The default Desired capacity is 1, Minimum capacity ->1, Maximum capacity -> 3 and there is no scaling policy. Due to this when load increases, the number of "BBBApplicationStack" EC2 instance donot increases.

Do we have to Manually create the scaling policy?
<img width="1792" alt="Screenshot 2020-12-12 at 12 39 28 AM" src="https://user-images.githubusercontent.com/20592184/101944294-7f6f2380-3c12-11eb-9b5b-4b9113fcc3ac.png">

**Comment by couchgott** [comment]
hi @vsinghal339,

take a look at #40 

that will give you some ideas why autoscaling of the apps is a "planned" processes like described at the readme.
