### ISSUE TITLE
Error while starting the meeting

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#54]
I have deployed the fresh setup with some modifications in the files to rebrand the actual bigbluebutton

Changes: 
1. File: templates/bbb-on-aws-bbbappscalable.template.yaml
Line: 375: 
**From**  "wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s $instance_fqdn -e ${BBBOperatorEMail} -c $turn_fqdn:$turnsecret" 
**to**  "wget -qO- https://bbb-install.s3.us-east-2.amazonaws.com/bbb-install-v2.sh | bash -s -- -v xenial-220 -s $instance_fqdn -e ${BBBOperatorEMail} -c $turn_fqdn:$turnsecret"

2. File: templates/bbb-on-aws-bbbappsingle.template.yaml, Line: 330 with same changes
3. File: templates/bbb-on-aws-bbbturn.template.yaml, Line: 308 with same changes

This 'https://bbb-install.s3.us-east-2.amazonaws.com/bbb-install-v2.sh' file has exactly the same code as in default file " https://ubuntu.bigbluebutton.org/bbb-install.sh" except following lines:

`sed -i 's/clientTitle:.*/clientTitle: SWYE360/g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    sed -i 's/appName:.*/appName: SWYE360/g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    sed -i 's/copyright:.*/copyright: " 2020 SWYE360 Learning Platform"/g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    sed -i 's/helpLink:.*/helpLink: https:\/\/www.swye360.com\/virtual-classroom-help/g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    sed -i 's/defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%<\/b>!.*/defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%<\/b>!/g' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    sed -i 's/defaultWelcomeMessageFooter=.*/defaultWelcomeMessageFooter=/g' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    wget -O /var/www/bigbluebutton-default/default.pdf https://bbb-install.s3.us-east-2.amazonaws.com/default.pdf
    wget -O /var/www/bigbluebutton-default/favicon.ico https://bbb-install.s3.us-east-2.amazonaws.com/favicon.ico
    wget -O /var/www/bigbluebutton-default/images/favicon.png https://bbb-install.s3.us-east-2.amazonaws.com/favicon.png`

The whole setup runs perfectly and deployed without any errors. I checked the events logs in autoscaling groups. But when i go to start session through greenlight, it shows 'Oops, there was an error when starting the meeting!'. I run destroy command and again run the setup command, but without any success

This setup used to work 2 months back but now is not working. Is there any way to debug?

**Comment by couchgott** [comment]
Hi @vsinghal339,

a good starting point for debuggin is to take a look at the logs collected in cloudwatch logs. 
you should find logs for all related services in there. 
the error itself can mean a lot of different things. to clarify try to use a setup without your config customizations. if that works, then most likely some of the customizations is errorous. work step by step through your custom code and check if the configs look good after each of your sed commands. 
for that amount of sed. i would rather place a customzed config at s3 and sideload from there. much easier to maintain. 

cheers!
