### ISSUE TITLE
Multiply Greenlights 

### ISSUE THREAD

**Issue by georgethegreatat** [aws-samples/aws-scalable-big-blue-button-example#56]
Hi.
In my case I need to create a new Greenlight container for each one of my clients.
How it's working for example: Client registered → get his personal link to BBB (on AWS) → Link in route53 is pointed exactly to the new container with Greenlight (container creating will be triggering from our side).

I need some info how to start it. In my own I think we need to create new template for auto-scaling group (change min, max, desire value each time when new client coming) what will create new greenlight container instance, new DB and will point greenlight to scalelite balancer with right secret key, and then create new DNS record in route53.

**Describe the solution you'd like**

I think we need to create bash script (ex. add_new_greenlight.sh) what will be running with command: ./add_new_greenlight.sh -p (aws-cli profile name) -e (operator email what would be admin email in greenlight) -h (DNS Zone) -s (CF stack name) -d my.domain.com

(Operator email should be greenlight admin email)

Does anyone do it before or can help me to give some info how to create this script correct ?

Thank you.

**Comment by couchgott** [comment]
Hey @georgethegreatat 

why do you need one greenlight frontend per client? and what are the actual requirements for each of them? 
Even with scaling the frontend up. you'll still have one single Database and Scalelite system. so it would still be single-tenant. 

if you think about multi dendancy. i would actually recomment to deploy the system multible times.

**Comment by georgethegreatat** [comment]
Hi @couchgott 

I wanna to create a template for deployment instance with Greenlight and DB containers on board. That will give to each one of our clients access only to personal records through greenlight (tested). And doesn't matter about only one scalelite lb, it can balance conferences from any numbers of greenlights to nodes. I'm testing nodes-scaling right now and it's working with my target scaling and my type of nodes.

Thats why i'm asking about it.

**Comment by couchgott** [comment]
@georgethegreatat 

scalelite is not only load balancing to the instances but also handling that the recordings from each instance is placed at the shared storage to provide access through greenlight. so if you want to seperate recordings multi-tenant you'll need to use seperated scalelite and EFS shares as well.

**Comment by couchgott** [comment]
ok. only if having recordings "not shown on frontend" is not enough. 
If you only want to seperate greenlight and it's DB i would recommend having a Service and a DB Instance for each of your clients. you can add each to the Cloudformation resources or .. if you'll have a lot of clients. use a Cloudformation stack for each of them importing Infos/Outputs/Exports from your "backplane" Cloudformation stack. indeed some work to do to change the code provided here to fit that need. but not horrible to do so :)

**Comment by couchgott** [comment]
closing due inactivity
