### ISSUE TITLE
Monitoring - Grafana

### ISSUE THREAD

**Issue by parrajeremy** [aws-samples/aws-scalable-big-blue-button-example#57]
Any help on getting this running would be much appreciated. 
https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/

To date I attempted to get this working via bbb-on-aws-bbbappscalable.template.yaml
          # Grafana
          mkdir ~/bbb-monitoring
          cd ~/bbb-monitoring
          sudo docker-compose up -d
          aws s3 cp s3://${BBBStackBucketStack}/monitoring.nginx /etc/bigbluebutton/nginx/monitoring.nginx

This does not seem to do the trick. As an aside any direction on connect to EC2 instance would be helpful, i.e. username?

**Comment by couchgott** [comment]
Sorry @parrajeremy i do not have any knowledge of that exporter. 
You can connect to the EC2 instance using Systems Manager (Session Manager) and you'll be logged in right away. sudo permissions are also granted. 

hope that helps ;)

**Comment by parrajeremy** [comment]
Thanks @couchgott. I'll post back when I get this working. Cheers.

**Comment by parrajeremy** [comment]
@couchgott  I have this working. Here are my steps following along with https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/

1. mkdir  aws-scalable-big-blue-button-example/monitoring
2. cp extras/all_in_one_monitoring/* aws-scalable-big-blue-button-example/monitoring/* 
3. in setup.sh add
...
`aws s3 sync --profile=$BBBPROFILE --exclude=".DS_Store" ./monitoring s3://$SOURCE`
...

4. in bbb-on-aws*.yml add following (I added after "# create script scalelite-handler" so we have SEVER variable)
a. Install docker and docker compose
 `          # Install Docker Compose
          apt-get update
          apt-get --yes --force-yes install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg-agent \
              software-properties-common

          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

          add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"

          apt-get update
          apt-get --yes --force-yes install docker-ce docker-ce-cli containerd.io
          curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose`

b. Install Monitoring
`       # Monitoring 
          mkdir /bbb-monitoring
          aws s3 cp s3://${BBBStackBucketStack}/docker-compose.yaml /bbb-monitoring/docker-compose.yaml
          aws s3 cp s3://${BBBStackBucketStack}/prometheus.yaml /bbb-monitoring/prometheus.yaml
          sed -i "s/example.com/conference.session.savvyreading.com/g" /bbb-monitoring/docker-compose.yaml
          sed -i "s/example.com/conference.session.savvyreading.com/g" /bbb-monitoring/prometheus.yaml
          touch /bbb-monitoring/bbb_exporter_secrets.env
          echo "API_BASE_URL=$SERVER" >> /bbb-monitoring/bbb_exporter_secrets.env
          echo "API_SECRET=$SECRET" >> /bbb-monitoring/bbb_exporter_secrets.env
          cd /bbb-monitoring
          docker-compose up -d
          touch /etc/bigbluebutton/nginx/monitoring.nginx
          echo "# BigBlueButton monitoring" >> /etc/bigbluebutton/nginx/monitoring.nginx
          echo "location /monitoring/ {" >> /etc/bigbluebutton/nginx/monitoring.nginx
          echo "proxy_pass http://127.0.0.1:3001/;" >> /etc/bigbluebutton/nginx/monitoring.nginx
          echo "include proxy_params;" >> /etc/bigbluebutton/nginx/monitoring.nginx
          echo "}" >> /etc/bigbluebutton/nginx/monitoring.nginx

          bbb-conf --restart`

5. Finally you can access monitoring at SERVER\monitoring, i.e. this is monitoring for a single instance. configure according to https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/#6-setup-grafana

**Comment by couchgott** [comment]
ty for your step-by-step instructions. i'll close the ticket itself. lets keep this at the archive. 👍
