### ISSUE TITLE
What changes are required to deploy in existing VPC?

### ISSUE THREAD

**Issue by ayuryogalifein** [aws-samples/aws-scalable-big-blue-button-example#61]
Could you let me know what changes are required to deploy in existing VPC with NAT gateway configured for two AZ

**Comment by couchgott** [comment]
Hey, 

first of all setup your VPC and Nat Gateway Routes and so on as needed. then set within parameter file: 

https://github.com/aws-samples/aws-scalable-big-blue-button-example/blob/main/bbb-on-aws-param.json

   
    "BBBVPCs": "ID OF VPC",
    "BBBPrivateApplicationSubnets": "IDSUBNET1, IDSUBNET2 ",
    "BBBPrivateDBSubnets": "IDSUBNET3, IDSUBNET4", (or IDSUBNET1/2 again, you can use the same if you need/like)
    "BBBPublicApplicationSubnets": "IDSUBNET1PUB, IDSUBNET2PUB",
    "BBBNumberOfAZs": 2,
  

That's basically all you need to set. 

Cheers!

**Comment by ayuryogalifein** [comment]
@couchgott Thanks a lot for your quick response. Will try it and let you know. 

Not sure why the network stack is failing when I am deploying at Mumbai location. It failed at point while creating the NAT gateway. Is it a possibility of not enough elastic IP available?

**Comment by couchgott** [comment]
Could be. You should see the detailed error message when you browse (i always use the console here for that cause its easier to digest) to the cloudformation sub stack deploying the network infra and look at the events tab.

**Comment by couchgott** [comment]
can you check and debug similar to what i tried to point out in #1

**Comment by borhanreo** [comment]
I am facing same problem  deployment fail for stack creation

**Comment by ayuryogalifein** [comment]
@couchgott Thanks a lot. I could resolve after following the guidance. Really efficient deployment script
