### ISSUE TITLE
Update BBBDBEngineVersion to 10.11

### ISSUE THREAD

**Issue by novastream** [aws-samples/aws-scalable-big-blue-button-example#63]
**Describe the bug**
The Aurora PostgreSQL version 10.7 is no longer availible (2021-01-31) in RDS and is automatically updated to 10.11. 

We should update the BBBDBEngineVersion parameter in bbb-on-aws-param.json from 10.7 to 10.11.

**To Reproduce**
1. Run the installation
2. Login to AWS and head to RDS

Don't know if it's possible to install 10.7 at all at this moment?

**Expected behavior**
It should install as expected.

**Comment by bklein1** [comment]
I am testing it with the latest Aurora PostgreSQL version 10.14 now. @couchgott I could not find a list of supported PostgreSQL versions. I will also be testing an upgrade from 10.14 to 12.4 afterwards.

**Comment by couchgott** [comment]
yes. the minor PostgreSQL versions are not listed at the Big Blue Button/Greenlight documentation. i would just do a test and then change the param. Greenlight is not doing weird DB stuff so i guess we're kind of safe.
