### ISSUE TITLE
Write error saving DB on disk: No space left on device

### ISSUE THREAD

**Issue by novastream** [aws-samples/aws-scalable-big-blue-button-example#66]
**Describe the bug**
Today we got a timeout 408 error when trying to start new rooms. Rooms that where already started was not affected by this.
When all the meetings where over I tried to restart bbb with bbb-conf --restart but it freezed on stopping bbb.
We restarted the AppStack instance and everything seems to be wokring again but we want to find the error so we can try to fix it.

These errors where looping before restart on our Redis server (cache.t3.medium):

> Background saving error

> Write error saving DB on disk: No space left on device

We did also find that we where using 100% of / on our AppStack (t3.2xlarge):

> /dev/nvme0n1p1   20G   20G   50M 100% /

> /dev/nvme1n1p1   50G   20G   28G  42% /var/bigbluebutton

**To Reproduce**
1. Host 5-15 meetings with 8-15 people
2. Wait for 408 timeout error
3. Restart bbb with bbb-conf --restart

**Expected behavior**
Server should not give 408 timeout error

**Comment by novastream** [comment]
This issue is temporary resolved.

We did stop the AppStack instance so it could be terminated and replaced by the AWS Auto Scaling rule.

Once we got a new instance we increased the nvme0n1p1 partition from 20 GB to 100 GB and everything seems to be working now. We will keep a close eye on this partition and see if it starts growing again.

**Comment by couchgott** [comment]
hey, 

do you have any information which path did eat up the 20G from "/" 
would be interesting to evaluate as an easy fix could be to add 1) another mount/volume if this is related to another (temp) data dir or 2) add just an parameter for / volume size. 

Cheers!

**Comment by novastream** [comment]
> 
> 
> hey,
> 
> do you have any information which path did eat up the 20G from "/"
> would be interesting to evaluate as an easy fix could be to add 1) another mount/volume if this is related to another (temp) data dir or 2) add just an parameter for / volume size.
> 
> Cheers!

Some of the errors keeps comming back, the 6gb partition is now growing again and is up to 30 GB and the default.pdf has disappeared and uploads dosen't work anymore so we had to pull the plug on this project and use a dedicated server setup instead.

**Comment by couchgott** [comment]
i think "2)" will help to be there to ensure for larger setups the root volume to be in a reasonable size. 
it sounds like some of the DBs Big Blue Button is installing keeps growing. the MongoDB or Redis installed with /var/lib/ paths. 
just an educated guess and nothing we can solve out of the deployment sample. more related to the actual Big Blue Button application.

**Comment by couchgott** [comment]
fixed with version 2.3.0
