### ISSUE TITLE
Cloud Formation error on setup

### ISSUE THREAD

**Issue by odejinmisa** [aws-samples/aws-scalable-big-blue-button-example#67]
**Describe the bug**
I encounter consistent error on cloud formation with error below

"
Embedded stack arn:aws:cloudformation:us-east-2:734928534788:stack/samstack1-BBBECSStack-WIAQ4K0V9OXO/9b389510-716e-11eb-82c3-024874579a58 was not successfully created: The following resource(s) failed to create: [BBBECSCapacityProvider].
--
"

**To Reproduce**

./setup.sh -p user1 -e support@examble.com -h Z05115161FM7Y5SVAYMDR -s samstack1 -d example.ng

I have tried granting all permissions I know it might required.

Kindly help me out on this issue.

![Screenshot 2021-02-18 000535](https://user-images.githubusercontent.com/62740154/108279691-4953a000-717d-11eb-9e48-b7f231764620.jpg)
![Screenshot 2021-02-18 000542](https://user-images.githubusercontent.com/62740154/108279695-4b1d6380-717d-11eb-9ffd-14c098a9160d.jpg)

**Comment by AwaleRohin** [comment]
Got into the same issue and could not apply the solutions provided in [#1]
My configuration:
hosted zone : myDomain.com
BBBDomainName :meeting.myDomain.com

Both are available at route53. What am I missing here?


```
+ grep -m 1 'has address 13.126.225.66'
+ sleep 5
+ host tu-5l26l4.meeting.myDomain.com
+ grep -m 1 'has address 13.126.225.66'
+ sleep 5
+ host tu-5l26l4.meeting.myDomain.com
+ grep -m 1 'has address 13.126.225.66'
+ sleep 5
```

**Comment by couchgott** [comment]
are you using an AWS registered or "external" Domain?
if 2nd. please check if the AWS DNS Servers (ref: Documentation) are properly registered and the name resolution is working from you or test devices (or internet test suites) 

Cheers!

**Comment by AwaleRohin** [comment]
The main domain `myDomain.com` is registered from `namecheap` and we have ns from aws there.
And the sub domain `meeting.myDomain.com` is configured from route53 and name resolution is also working.

**Comment by couchgott** [comment]
can you see tu-5l26l4.meeting.myDomain.com added to the route53 domain and is it resolvable for you while the setup runs?

**Comment by AwaleRohin** [comment]
yes there is `tu-5l26l4.meeting.myDomain.com` being added to route53 and it was only resolvable once out of few tries that too was at the beginning when  `tu-5l26l4.meeting.myDomain.com` was added to route53 but after few minutes it was not resolvable even though it was still in route53.

**Comment by couchgott** [comment]
if you deploy again, can you check if the hostname gets resolvable while the turn server is deploying? 
the only reason i can think about is, that it takes too long until it can be resolved and then the deployment is cancelled.

**Comment by couchgott** [comment]
can you also check the nested stacks events for the error causing the rollback and post it here, jic

**Comment by AwaleRohin** [comment]
Hostname do get resolved when turn server is deploying
![hostname](https://i.ibb.co/L0p2hNj/IMG-2753.jpg)

And this is screenshot of `/var/log/cloud-init-output.log`
![output-log](https://i.ibb.co/RQJm1Zn/IMG-2754.jpg)

Stack Events
![stack-events](https://i.ibb.co/VqFrfR1/Screen-Shot-2021-02-28-at-12-55-12-PM.png)

**Comment by couchgott** [comment]
This is the Parent stacks output. 
Please check the BBBTurnStack output for more details. hint: it might be that you have to filter for deleted stacks to see it

**Comment by AwaleRohin** [comment]
![image](https://i.ibb.co/gWLYrb5/Screen-Shot-2021-03-16-at-10-59-42-AM.png)

**Comment by couchgott** [comment]
can you please check on the turn server itself if the hostname is resolving. 
you can use the Systems Manager Session Manager to log into the Instance (Console -> EC2 -> Turn instance -> Connect -> Session Manager)

**Comment by couchgott** [comment]
closing due inactivity
