### ISSUE TITLE
media could not reach the server error - 1020

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#71]
Default setup with video & audio is working in Google chrome but in safari, ios, ipad it shows error - 1020

**Comment by couchgott** [comment]
Sorry this is an Big Blue Button application question. 
please check if https://test.bigbluebutton.org/ works for you.
if not, please file a ticket on the big blue button issue tracker or check the recommendations here: https://github.com/bigbluebutton/bigbluebutton/issues/6797 

And: https://github.com/bigbluebutton/bigbluebutton/issues/10746#issuecomment-719087723

**Comment by couchgott** [comment]
closing due inactivity.
