### ISSUE TITLE
"ResourceStatusReason": "Embedded stack arn:aws:cloudformation:ap-south-1:186828894056:stack/cloudformation2-BBBNetworkStack-6LV2DJOIC9I8/ef83a860-9092-11eb-b682-0a00cbb491c0 was not successfully created: The following resource(s) failed to create: [BBBPrivateDBSubnet1RouteTableAssociation, BBBPrivateApplicationSubnet1RouteTableAssociation, BBBPublicApplicationSubnet3RouteTableAssociation, BBBPrivateDBSubnet3RouteTableAssociation, BBBNatGateway1EIP, BBBPublicApplicationSubnet2RouteTableAssociation

### ISSUE THREAD

**Issue by censation** [aws-samples/aws-scalable-big-blue-button-example#74]
I tried running the setup script and the script ran till it copied all the files to S3 and I even received a mail back to the given email from the Notification service but then I ran into this error while creating the network Stack

"ResourceStatusReason": "Embedded stack arn:aws:cloudformation:ap-south-1:186828894056:stack/cloudformation2-BBBNetworkStack-6LV2DJOIC9I8/ef83a860-9092-11eb-b682-0a00cbb491c0 was not successfully created: The following resource(s) failed to create: [BBBPrivateDBSubnet1RouteTableAssociation, BBBPrivateApplicationSubnet1RouteTableAssociation, BBBPublicApplicationSubnet3RouteTableAssociation, BBBPrivateDBSubnet3RouteTableAssociation, BBBNatGateway1EIP, BBBPublicApplicationSubnet2RouteTableAssociation

[output2.txt](https://github.com/aws-samples/aws-scalable-big-blue-button-example/files/6222070/output2.txt)
This is the stack events copied onto a file.

**Comment by bklein1** [comment]
Can you please add the events for the nested network stack? The failure details are not part of the parent stack.

**Comment by censation** [comment]
I have appended a txt file, that contains the entire stack events. Is that not what you're asking? 
How would I get the nested network stack events if that txt file is not the one?

**Comment by censation** [comment]
I changed all the subnet CIDR blocks from 10.x.x.x to 30.x.x.x and finally ended up having the following error in creation of the network stack

Embedded stack arn:aws:cloudformation:ap-south-1:186828894056:stack/cloudformation5-BBBNetworkStack-GZQ1VFYOVK8Z/3745fd40-9135-11eb-a6b4-02de9c8f35e4 was not successfully created: The following resource(s) failed to create: [BBBNatGateway1EIP, BBBDefaultPublicRoute].

**Comment by censation** [comment]
"ResourceStatusReason": "Embedded stack arn:aws:cloudformation:ap-south-1:055591860752:stack/CENMeetStack3-BBBFontendAppsStack-7FMZWQUQ9F99/ca5eed60-91e1-11eb-9e0b-0ae9acba2152 was not successfully created: The following resource(s) failed to create: [BBBPublicCertificateDNSRecord, BBBSMTPUser, BBBScaleliteExecutionRole, BBBPublicIssuedCertificate, BBBSESVerificationRecords, BBBScaleliteALB, BBBFrontendALB]. ",
            "StackName": "CENMeetStack3",
            "Timestamp": "2021-03-31T05:27:54.494Z",
            "ResourceStatus": "CREATE_FAILED",  ==> PublicCertificateDNSRecord,
            "LogicalResourceId": "BBBFontendAppsStack",
            "EventId": "BBBFontendAppsStack-CREATE_FAILED-2021-03-31T05:27:54.494Z",
            "PhysicalResourceId": "arn:aws:cloudformation:ap-south-1:055591860752:stack/CENMeetStack3-BBBFontendAppsStack-7FMZWQUQ9F99/ca5eed60-91e1-11eb-9e0b-0ae9acba2152",
            "ResourceProperties": "{\"TemplateURL\":\"https://s3.amazonaws.com/cenmeetstack3-sources-bbbstackbucket-1buwyyo5pc5l9/bbb-on-aws-frontendapps.template.yaml\",\"Parameters\":{\"BBBSesRegion\":\"AWS::NoValue\",\"BBBECSInstanceType\":\"t3a.medium\",\"BBBRDSDBConnectionSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBRDSDBConnectionSecret-3Wv9KM2SJbZU-6RyFqY\",\"BBBSharedStorageFS\":\"fs-c5381a14\",\"BBBVPCs\":\"vpc-06c5b2197932de0c6\",\"BBBACMCertProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBACMCertStack-MACIWKD1OVTE-cert-provider\",\"BBBScaleliteCPU\":\"1024\",\"BBBGreenlightDesiredReplicas\":\"1\",\"BBBTurnSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBTurnSecret-hvuyoltezmX2-NZyj9P\",\"BBBScalelitePollerImage\":\"blindsidenetwks/scalelite:v1.0.7-poller\",\"BBBgreenlightImage\":\"bigbluebutton/greenlight:release-2.7.20\",\"BBBEnvironmentStage\":\"dev\",\"BBBSharedStorageAPunpublished\":\"fsap-0be372f50969c055b\",\"BBBScaleliteELBSecurityGroup\":\"sg-075435049c616e118\",\"BBBNotificationTopic\":\"arn:aws:sns:ap-south-1:055591860752:CENMeetStack3-BBBNotificationTopic-1LA3M9CD2XBDR\",\"BBBGreenlightCPU\":\"512\",\"BBBPrivateApplicationSubnets\":\"subnet-0c4b2092459db0297,subnet-0caefca1a88e45f5b,subnet-05acddad6f4b65d16\",\"BBBScaleliteDesiredReplicas\":\"1\",\"BBBScaleliteApiImage\":\"blindsidenetwks/scalelite:v1.0.7-api\",\"BBBOperatorEMail\":\"manjuraj.v@gmail.com\",\"BBBScaleliteImporterImage\":\"blindsidenetwks/scalelite:v1.0.7-recording-importer\",\"BBBDomainName\":\"eventenergies.com\",\"BBBScaleliteMinReplicas\":\"1\",\"BBBSharedStorageAPspool\":\"fsap-0ec976223c51ede5f\",\"BBBHostedZone\":\"Z29BU1I287KH4O\",\"BBBECSTaskSecurityGroup\":\"sg-0026562117c8f7084\",\"BBBGreenlightMinReplicas\":\"1\",\"BBBGreenlightMemory\":\"1024\",\"BBBRDSDBSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBRDSDBSecret-4oLPPaWL22sf-jQzhDv\",\"BBBSESProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBSESProviderStack-68GJ1KBL1U3H-ses-provider\",\"BBBScaleliteNginxImage\":\"blindsidenetwks/scalelite:v1.0.7-nginx\",\"BBBApplicationLogsGroup\":\"/CENMeetStack3/applicationlogs\",\"BBBSharedStorageAPrecordings\":\"fsap-0174e493c91fa5f0b\",\"BBBSMTPSecretProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBSESProvider-BBBSMTPSecretProvider-1D5GFO076RC5R\",\"BBBECSCluster\":\"CENMeetStack3-BBBECSStack-1JAEVEGILEAKS-ECSCluster\",\"BBBDBName\":\"frontendapp\",\"BBBCacheDBPort\":\"6379\",\"BBBPublicApplicationSubnets\":\"subnet-0c4cdd67b1f43ec41,subnet-01f9620a6ff9ea8c2,subnet-073d5d439e55f5301\",\"BBBScaleliteMemory\":\"2048\",\"BBBGreenlightMaxReplicas\":\"3\",\"BBBScaleliteMaxReplicas\":\"3\",\"BBBSharedStorageAPpublished\":\"fsap-08205cf0ce77b44f5\",\"BBBFrontendELBSecurityGroup\":\"sg-0a7e69c9c35bddb4b\",\"BBBCacheDBAddress\":\"cen-bb-1vi2o184y6kq8.lukznc.0001.aps1.cache.amazonaws.com\"},\"Tags\":[{\"Value\":\"BBBFrontendApplicationStack-bbbonaws\",\"Key\":\"Name\"},{\"Value\":\"bbbonaws\",\"Key\":\"Environment\"},{\"Value\":\"dev\",\"Key\":\"Stage\"}]}",


Have also done this DNS settings for my domain.
https://gitmemory.com/issue/aws-samples/aws-scalable-big-blue-button-example/52/747660283

**Comment by censation** [comment]
> ```
>         "ResourceStatusReason": "Embedded stack arn:aws:cloudformation:ap-south-1:055591860752:stack/CENMeetStack3-BBBFontendAppsStack-7FMZWQUQ9F99/ca5eed60-91e1-11eb-9e0b-0ae9acba2152 was not successfully created: The following resource(s) failed to create: [BBBPublicCertificateDNSRecord, BBBSMTPUser, BBBScaleliteExecutionRole, BBBPublicIssuedCertificate, BBBSESVerificationRecords, BBBScaleliteALB, BBBFrontendALB]. ",
>         "StackName": "CENMeetStack3",
>         "Timestamp": "2021-03-31T05:27:54.494Z",
>         "ResourceStatus": "CREATE_FAILED",  ==> PublicCertificateDNSRecord,
>         "LogicalResourceId": "BBBFontendAppsStack",
>         "EventId": "BBBFontendAppsStack-CREATE_FAILED-2021-03-31T05:27:54.494Z",
>         "PhysicalResourceId": "arn:aws:cloudformation:ap-south-1:055591860752:stack/CENMeetStack3-BBBFontendAppsStack-7FMZWQUQ9F99/ca5eed60-91e1-11eb-9e0b-0ae9acba2152",
>         "ResourceProperties": "{\"TemplateURL\":\"https://s3.amazonaws.com/cenmeetstack3-sources-bbbstackbucket-1buwyyo5pc5l9/bbb-on-aws-frontendapps.template.yaml\",\"Parameters\":{\"BBBSesRegion\":\"AWS::NoValue\",\"BBBECSInstanceType\":\"t3a.medium\",\"BBBRDSDBConnectionSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBRDSDBConnectionSecret-3Wv9KM2SJbZU-6RyFqY\",\"BBBSharedStorageFS\":\"fs-c5381a14\",\"BBBVPCs\":\"vpc-06c5b2197932de0c6\",\"BBBACMCertProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBACMCertStack-MACIWKD1OVTE-cert-provider\",\"BBBScaleliteCPU\":\"1024\",\"BBBGreenlightDesiredReplicas\":\"1\",\"BBBTurnSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBTurnSecret-hvuyoltezmX2-NZyj9P\",\"BBBScalelitePollerImage\":\"blindsidenetwks/scalelite:v1.0.7-poller\",\"BBBgreenlightImage\":\"bigbluebutton/greenlight:release-2.7.20\",\"BBBEnvironmentStage\":\"dev\",\"BBBSharedStorageAPunpublished\":\"fsap-0be372f50969c055b\",\"BBBScaleliteELBSecurityGroup\":\"sg-075435049c616e118\",\"BBBNotificationTopic\":\"arn:aws:sns:ap-south-1:055591860752:CENMeetStack3-BBBNotificationTopic-1LA3M9CD2XBDR\",\"BBBGreenlightCPU\":\"512\",\"BBBPrivateApplicationSubnets\":\"subnet-0c4b2092459db0297,subnet-0caefca1a88e45f5b,subnet-05acddad6f4b65d16\",\"BBBScaleliteDesiredReplicas\":\"1\",\"BBBScaleliteApiImage\":\"blindsidenetwks/scalelite:v1.0.7-api\",\"BBBOperatorEMail\":\"manjuraj.v@gmail.com\",\"BBBScaleliteImporterImage\":\"blindsidenetwks/scalelite:v1.0.7-recording-importer\",\"BBBDomainName\":\"eventenergies.com\",\"BBBScaleliteMinReplicas\":\"1\",\"BBBSharedStorageAPspool\":\"fsap-0ec976223c51ede5f\",\"BBBHostedZone\":\"Z29BU1I287KH4O\",\"BBBECSTaskSecurityGroup\":\"sg-0026562117c8f7084\",\"BBBGreenlightMinReplicas\":\"1\",\"BBBGreenlightMemory\":\"1024\",\"BBBRDSDBSecret\":\"arn:aws:secretsmanager:ap-south-1:055591860752:secret:BBBRDSDBSecret-4oLPPaWL22sf-jQzhDv\",\"BBBSESProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBSESProviderStack-68GJ1KBL1U3H-ses-provider\",\"BBBScaleliteNginxImage\":\"blindsidenetwks/scalelite:v1.0.7-nginx\",\"BBBApplicationLogsGroup\":\"/CENMeetStack3/applicationlogs\",\"BBBSharedStorageAPrecordings\":\"fsap-0174e493c91fa5f0b\",\"BBBSMTPSecretProviderArn\":\"arn:aws:lambda:ap-south-1:055591860752:function:CENMeetStack3-BBBSESProvider-BBBSMTPSecretProvider-1D5GFO076RC5R\",\"BBBECSCluster\":\"CENMeetStack3-BBBECSStack-1JAEVEGILEAKS-ECSCluster\",\"BBBDBName\":\"frontendapp\",\"BBBCacheDBPort\":\"6379\",\"BBBPublicApplicationSubnets\":\"subnet-0c4cdd67b1f43ec41,subnet-01f9620a6ff9ea8c2,subnet-073d5d439e55f5301\",\"BBBScaleliteMemory\":\"2048\",\"BBBGreenlightMaxReplicas\":\"3\",\"BBBScaleliteMaxReplicas\":\"3\",\"BBBSharedStorageAPpublished\":\"fsap-08205cf0ce77b44f5\",\"BBBFrontendELBSecurityGroup\":\"sg-0a7e69c9c35bddb4b\",\"BBBCacheDBAddress\":\"cen-bb-1vi2o184y6kq8.lukznc.0001.aps1.cache.amazonaws.com\"},\"Tags\":[{\"Value\":\"BBBFrontendApplicationStack-bbbonaws\",\"Key\":\"Name\"},{\"Value\":\"bbbonaws\",\"Key\":\"Environment\"},{\"Value\":\"dev\",\"Key\":\"Stage\"}]}",
> ```
> 
> Have also done this DNS settings for my domain.
> https://gitmemory.com/issue/aws-samples/aws-scalable-big-blue-button-example/52/747660283

@bklein1  can you help us in this regard and we are stuck

**Comment by bklein1** [comment]
Hi @censation, nested stacks are a way to group components together. When this is used you have a main stack that manages (create, update, delete) additional stack (in this case: Network, Database, ECS, etc.). You can find those stacks and their events in the console as well as via the CLI.

For the Network Stack and the failed component there I would guess that your Account ran out of Elastic IPs ([per default this limit is set to 5](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html)) for the Nat Gateway. But that is just a guess. I need to see the events, or status reason for the components.

The same applies to the BBBFontendAppsStack.

**Comment by censation** [comment]
Thanks for replying @bklein1.
The issue was as you mentioned, it was a shortage of EIPs. I just freed out some and was able to get through it.
Thanks.
