### ISSUE TITLE
Database substack fails when using a serverless configuration

### ISSUE THREAD

**Issue by Mikitin00** [aws-samples/aws-scalable-big-blue-button-example#75]
The DB engine version for a serverless postgress configuration should be 10.12 and it is failing.

<img width="995" alt="Screen Shot 2021-03-31 at 4 20 31 PM" src="https://user-images.githubusercontent.com/74611919/113206927-0be33780-923e-11eb-8f2f-93ebe3d20d23.png">

I did change the parameter BBBDBEngineVersion but it doesn't take it when serverless.

**Comment by couchgott** [comment]
i need to check that. sorry for the delay.

**Comment by Mikitin00** [comment]
It is a very easy fix. Just remove the double quotes in
BBBRDSDBParameterGroupPostgres12 and do an if statement for family so that
if it is serveless the family has to be aurora-postgresql10

**Comment by couchgott** [comment]
ty for the hint :)
