### ISSUE TITLE
Received response status [FAILED] from custom resource. Message returned: SES domain identity MyDomain.com already exists in region

### ISSUE THREAD

**Issue by ojhaashish13** [aws-samples/aws-scalable-big-blue-button-example#77]
**Describe the bug**
Received response status [FAILED] from custom resource. Message returned: SES domain identity MyDomain.com already exists in region us-west-2 (RequestId: ab3f7656-d7db-45f8-89a8-b3bfbdc4d123)

**To Reproduce**
1. Clone the repo
2. Run the setup command like this:

`./setup.sh -p default -e devwork@MyDomain.com  -h Z1Q......... -s bbb-stack -d MyDomain.com `

**Expected behavior**
To complete the setup as the documentation. But it is failing.

**Screenshots**
![Screenshot 2021-04-21 at 1 23 57 PM](https://user-images.githubusercontent.com/6647624/115595748-4a03d200-a2a5-11eb-8541-b562f23b341e.png)
<img width="1312" alt="Screenshot 2021-04-21 at 1 28 04 PM" src="https://user-images.githubusercontent.com/6647624/115596378-078ec500-a2a6-11eb-8ce9-5042736ed96d.png">

**Additional context**
My hosted zone exists with the name MyDomain.com on Route 53 and it registered with AWS only and this hosted zone has multiple subdomains.
As per the command, I am passing my Hosted zone name and its Hosted Zone Id.
Please let me know, what I am doing wrong. Have already checked issue #1 but still unable to resolve the problem.

**Comment by couchgott** [comment]
Hey, 

did you already setup SES beforehand (for any other project) by yourself. this could be the cause. we currently do not check if the SES domain still needs validation which can cause that resource to fail. 
what you can do as a quickfix is to remove the SES validation part from the code and set the resulting variable manually using another paramter. 

i can change the code to a conditional validation for SES but that might take another week or two until i find time to do so.

**Comment by ojhaashish13** [comment]
Thanks for the reply.
Yes my domain is already verified in SES domain verification and I am using SES service.
<img width="1421" alt="Screenshot 2021-04-22 at 11 01 11 AM" src="https://user-images.githubusercontent.com/6647624/115737501-31a1bf00-a35a-11eb-884b-5071a6d60d02.png">

let me know, which template I need to modify and do I need to create any subdomain under my hosted zone?

**Comment by couchgott** [comment]
So basically comment 173 - 254

in here: 

`  BBBSMTPAccessSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'This is the BBB SMTP Login'
      SecretString: !Sub "{\"smtpusername\":\"${BBBUserAccessKey}\",\"smtppassword\":\"${BBBSMTPAccessKey}\"}"
`

You need to fill these 2 variables with the values from an existing SES/SMTP user. 

i will add conditions to this section when i find time during the next 2 weeks which will make it easier to use in the future.

**Comment by ojhaashish13** [comment]
Thanks for the reply. I did the changes as per the suggestions and re-run the script but still failing due to "**BBBPublicDomainValidationRecord**", should I comment this block from line 402-413 too?

`BBBPublicDomainValidationRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref BBBHostedZone
      RecordSets:
        - Name: !GetAtt BBBPublicCertificateDNSRecord.Name
          Type: !GetAtt BBBPublicCertificateDNSRecord.Type
          TTL: 60
          Weight: 1
          SetIdentifier: !Ref BBBPublicCertificate
          ResourceRecords:
            - !GetAtt BBBPublicCertificateDNSRecord.Value`


![Screenshot 2021-04-26 at 12 46 49 PM](https://user-images.githubusercontent.com/6647624/116120850-02f35380-a68e-11eb-841d-53d3fa8a8b09.png)

**Comment by couchgott** [comment]
Hi, 

yes, this needs to be commented out. Also similar to the SMTP user vars you need to define the ARN of the ACM cert via Parameter where it is used (e.g. at the ALB setups)

**Comment by couchgott** [comment]
maybe another thing to parameterize then (SES setup and ACM certs).

**Comment by ojhaashish13** [comment]
Thanks, I updated the frontend template by commenting the ACM code and passed the certificate ARN as a parameter.
It works and my stack deployed successfully.
However, I got one failed message for "BBBScaleliteTaskdefinition" not sure if it will impact my deployment. Please check and let me know if I need to update and re-deploy the stack.


`Resource template validation failed for resource BBBScaleliteTaskdefinition as the template has invalid properties. Please refer to the resource documentation to fix the template. Properties validation failed for resource BBBScaleliteTaskdefinition with message: #/Volumes/0: extraneous key [efsVolumeConfiguration] is not permitted #/Volumes/1: extraneous key [efsVolumeConfiguration] is not permitted #/Volumes/2: extraneous key [efsVolumeConfiguration] is not permitted #/Volumes/3: extraneous key [efsVolumeConfiguration] is not permitted`

<img width="1354" alt="Screenshot 2021-04-29 at 1 03 28 PM" src="https://user-images.githubusercontent.com/6647624/116590828-30d5d380-a8ec-11eb-8aee-b710d5cdae08.png">

**Comment by couchgott** [comment]
hey. i have no idea currently. let me see when i test the new version of the project during the next days.
