### ISSUE TITLE
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by Ghousecms** [aws-samples/aws-scalable-big-blue-button-example#78]
Cloud Formation stack is failing at Autoscaling, with the error message "Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement." is there any solution to resolve?

**Comment by couchgott** [comment]
Hi, 

which nested stack is failing and can you please post the exact error output? 

thy!

**Comment by couchgott** [comment]
closing due inactivity.
