### ISSUE TITLE
ECS resource fails to delete when bringing the stack down.

### ISSUE THREAD

**Issue by censation** [aws-samples/aws-scalable-big-blue-button-example#79]
Whenever I tried to bring the CloudFormation Stack down or rollback occurs, the ECS stack fails to delete. 

It says, 
Resource handler returned message: "Error occurred during operation 'DeleteClusters SDK Error: The Cluster cannot be deleted while Container Instances are active or draining. (Service: AmazonECS; Status Code: 400; Error Code: ClusterContainsContainerInstancesException; Request ID: 5af2a33d-502b-49ac-a2f1-9b2137aa9742; Proxy: null)'." (RequestToken: 9fd5ac59-3584-a25c-2ee5-14c56f0e0776, HandlerErrorCode: GeneralServiceException)

I understand there are some resources in use and that is why I am not able to delete the stack entirely.
Is there any way to deal with this issue by running the delete-stack command alone or some alternative?

**Comment by couchgott** [comment]
Hey @censation,

browse to Amazon ECS and lookup the cluster. if there are still tasks/services running you can delete them manually first and then try to delete the Cloudformation Stack. Does this work?

**Comment by censation** [comment]
Thanks for replying @couchgott 

I have tried manually deleting and it works just fine. But I wanted to do that automatically using the command line or by running a script. Is there any way you could do that?

**Comment by couchgott** [comment]
Hi,
this is a glitch with deleting ECS clusters i've seen before. it should work automatically using the destroy.sh or cli commands. 
sometimes it does not. but thats not intended ;)

**Comment by couchgott** [comment]
related to: https://github.com/aws/containers-roadmap/issues/631
