### ISSUE TITLE
Scalelite API to directly call Create Meeting API

### ISSUE THREAD

**Issue by vsinghal339** [aws-samples/aws-scalable-big-blue-button-example#8]
With this current Scalable architecture, The only way to create a session is through Greenlight frontend.

But if we setup Scalelite as a stand alone, then scalelite offers calling to APIs like createMeeting, JoinMeeting and get Recordings. How can we call these APIs without using Greenlight as a frontend

**Comment by couchgott** [comment]
Hi, 

the Scalelite is actually just forwarding the API calls to the BigBlueButton Instance selected for the next meeting. 
So you can use other frontends like [moodle](https://moodle.org/plugins/mod_bigbluebuttonbn) or just build your own frontend and utilize the [BigBlueButton API](https://docs.bigbluebutton.org/dev/api.html). Also please ref to the [Scalelite Documentation](https://github.com/blindsidenetworks/scalelite), there are some hints as well. 

Cheers!

**Comment by vsinghal339** [comment]
Hi,

In the case of custom frontend, What will be the target end point to hit the server.

Because only greenlight frontend is only server which is exposed publicaly and not scalelite server

**Comment by bklein1** [comment]
Hi,

Scalelite is exposed by an ALB as well. It is accessible using the scalelite subdomain. So you can replace conference.<your-domain> by scalelite.<your-domain> to call the scalelite APIS.

**Comment by vsinghal339** [comment]
Thanks I will check again
