### ISSUE TITLE
Same VPC for dual stack

### ISSUE THREAD

**Issue by yoU-Jay** [aws-samples/aws-scalable-big-blue-button-example#80]
How to reuse same VPC while dual stack is provisioned?

**Comment by couchgott** [comment]
Hey, 
what do you mean by dual stack?
Do you think about deploying the stack 2 times into the same Account?

**Comment by yoU-Jay** [comment]
Yes, more than 1 stack in the same account.
All stacks (>=2) should share VPC but with different subnet-groups for each stack.

**Comment by couchgott** [comment]
Hey, 

i haven't tried it but it "should" work if you precreate the additional subnets  and add the existing VPC and these subnets IDs at the parameters(-file). just ensure everything stays unique. Naming, subdomains,CIDR/Subnets you use, etc. 
please test first in a save environment!
How to reuse an existing VPC is also described at the readme in more detail :)
