### ISSUE TITLE
bigbluebutton auto scaling setup  error

### ISSUE THREAD

**Issue by suprobhat** [aws-samples/aws-scalable-big-blue-button-example#88]
hi everyone 
I am creating BBB auto-scaling error sowing

An error occurred (InvalidClientTokenId) when calling the ValidateTemplate operation: The security token included in the request is invalid.
[fail] ./templates/bbb-on-aws-bbbappscalable.template.yaml:

![1](https://user-images.githubusercontent.com/61926568/118635362-1dce6900-b7f1-11eb-9bfe-b3a26edde197.png)

aws cli user permision iam role permision
![2](https://user-images.githubusercontent.com/61926568/118635709-84538700-b7f1-11eb-9f60-9eee81a6bed6.png)

Please help me
Regards
suprobhat ganguly

any related document please send me my mail id: XXXXXX

**Comment by couchgott** [comment]
note: removed personal email from the issue. 

to the issue: it seems your Role or aws-cli setup on the Host you try to run the setup.sh from. 
do you use AWS SSO / User Federation in your environment? then make sure your securety token is up-to-date.

**Comment by couchgott** [comment]
also make sure you do have all needed permissions for Cloudformation and Cloudformation is allowed to set IAM permissions.

**Comment by suprobhat** [comment]
ok i will removed personal email
then i will add aws acount emil
then  setup script are run please help me

**Comment by couchgott** [comment]
Please follow the documentation to get your AWS Cli up and running on your linux instance before using the setup.sh script: 
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv1.html

then test your setup profile (-p) with a commend like:
"aws s3 ls --profile PROFILENAME" 

if this is working you can start using the setup.sh 

the issue is not related to the actual deployment or codebase from this project. afaics

**Comment by suprobhat** [comment]
Thanks, I'll check it out.

**Comment by suprobhat** [comment]
Hi 
couchgott 
  
some error sowing 
An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:ap-south-1:733049912274:stack/bbb-stack/0e455000-b875-11eb-9047-0a4bd10d9834 is in ROLLBACK_COMPLETE state and can not be updated.

![7](https://user-images.githubusercontent.com/61926568/118784584-c5a96c80-b8ad-11eb-91e4-265833ec47f1.png)

IAM USER full permission AWS Cloudformation Full accesses  but error sowing
![8](https://user-images.githubusercontent.com/61926568/118785112-29cc3080-b8ae-11eb-8ee9-d5ba45cac556.png)
 
Please help me

Regards
suprobhat ganguly

**Comment by couchgott** [comment]
you need to delete the errorous stacks before redeploy.

**Comment by suprobhat** [comment]
ok i will try

**Comment by suprobhat** [comment]
couchgott 
same error sowing

**Comment by couchgott** [comment]
are you using AWS SSO to login? This again looks like the Security Token got invalid/expired.

**Comment by couchgott** [comment]
closing due inactivity
