### ISSUE TITLE
What changes needs to be made in Order to get BBB-2.3 deployed

### ISSUE THREAD

**Issue by censation** [aws-samples/aws-scalable-big-blue-button-example#93]
Hello,

The clo8udformation is picking those images which are poinitng to BBB-2.2

Now that BBB-2.3 is released can you give us pointers as to which and file needs to be changed to make BBB-2.3 is deployed.

Regards,
censation

**Comment by couchgott** [comment]
Hi, 

you can set the BBB version of your choise to 2.3 using https://github.com/aws-samples/aws-scalable-big-blue-button-example/blob/main/bbb-on-aws-param.json
the default should already install bionical-2.3.0 on Ubuntu 18.04 though.

Chees!

**Comment by couchgott** [comment]
closing
