### ISSUE TITLE
Question regarding automatic depolyment

### ISSUE THREAD

**Issue by shankar-bavan** [aws-samples/aws-scalable-big-blue-button-example#94]
This is not Bug. sorry for opening issue for question.

I'm bit confused with automatic deployment guide. Could you please guide me

1. where should I host this repo  files ? on s3?
2. should I need to create cloud formation stack first ? if yes what is the template I should specify ?

**Comment by couchgott** [comment]
Hey @shankar-bavan 

1) you can clone this repo. the files are needed where you start the setup using the setup.sh. 
everything needed at S3 will be uploaded via that script automatically.

2. you should use the setup.sh from your device to start the deployment. please ensure to read through the prerequisites at the Readme.md of the repo.

hope this helps to get started :) 

Cheers!

**Comment by shankar-bavan** [comment]
Great. It's working :) Thank you so much

**Comment by shankar-bavan** [comment]
@couchgott I followed step-by-step guide

I got this error after 10-15 min

```
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name bbbexample

```

![image](https://user-images.githubusercontent.com/48729909/121378419-d014ce80-c960-11eb-8b6b-97851614d33d.png)
