### ISSUE TITLE
BBBScaleliteService and BBBgreenlightService failed to create resources with "Resource timed out error"

### ISSUE THREAD

**Issue by ojhaashish13** [aws-samples/aws-scalable-big-blue-button-example#96]
**Describe the bug**
BBBScaleliteService and BBBgreenlightService failed to create services with Resource timed out error.

**To Reproduce**
1. Clone the repository.
2. Run the command with the existing hosted zone and domain and existing ACM certificate.
3. Not using "fargate" or Serverless deployment for Greenlight and Scalelite.
4. Deployment json parameters are:

`{
  "Parameters" : {
    "BBBApplicationVersion": "bionic-230",
    "BBBApplicationInstanceOSVersion": "bionic-18.04",
    "BBBTurnInstanceOSVersion": "focal-20.04",
    "BBBECSInstanceType": "t3a.large",
    "BBBApplicationInstanceType": "c5.xlarge",
    "BBBApplicationDataVolumeSize": 50,
    "BBBApplicationRootVolumeSize": 20,
    "BBBTurnInstanceType": "t3a.medium",
    "BBBDBInstanceType": "db.t3.large",
    "BBBServerlessAuroraMinCapacity": 2,
    "BBBServerlessAuroraMaxCapacity": 4,
    "BBBCACHEDBInstanceType": "cache.t3.micro",
    "BBBVPCs": "10.1.0.0/16",
    "BBBPrivateApplicationSubnets": "10.1.5.0/24,10.1.6.0/24,10.1.7.0/24",
    "BBBPrivateDBSubnets": "10.1.9.0/24,10.1.10.0/24,10.1.11.0/24",
    "BBBPublicApplicationSubnets": "10.1.15.0/24,10.1.16.0/24,10.1.17.0/24",
    "BBBNumberOfAZs": 3,
    "BBBECSMaxInstances": 3,
    "BBBECSMinInstances": 1,
    "BBBECSDesiredInstances": 1,
    "BBBApplicationMaxInstances": 1,
    "BBBApplicationMinInstances": 1,
    "BBBApplicationDesiredInstances": 1,
    "BBBTurnMaxInstances": 1,
    "BBBTurnMinInstances": 1,
    "BBBTurnDesiredInstances": 1,
    "BBBDBName": "frontendapp",
    "BBBDBEngineVersion": "12.4",
    "BBBEnvironmentStage": "dev",
    "BBBEnvironmentName": "bbbonaws",
    "BBBEnvironmentType": "scalable",
    "BBBgreenlightImage": "bigbluebutton/greenlight:v2",
    "BBBScaleliteApiImage": "blindsidenetwks/scalelite:v1.1-api",
    "BBBScaleliteNginxImage": "blindsidenetwks/scalelite:v1.1-nginx",
    "BBBScalelitePollerImage": "blindsidenetwks/scalelite:v1.1-poller",
    "BBBScaleliteImporterImage": "blindsidenetwks/scalelite:v1.1-recording-importer",
    "BBBCacheAZMode": "cross-az",
    "BBBGreenlightMemory": 1024,
    "BBBGreenlightCPU": 512,
    "BBBScaleliteMemory": 2048,
    "BBBScaleliteCPU": 1024,
    "BBBSESValidated": true,
    "BBBACMCertArn": "arn:aws:acm:********ACM Cert ARN****************"
  }
}`

**Expected behavior**
It should deploy the template but throwing the error.

**Screenshots**
<img width="1348" alt="Screenshot 2021-06-10 at 5 05 41 PM" src="https://user-images.githubusercontent.com/6647624/121597833-27717800-ca0f-11eb-91e2-67c768ab4d6d.png">

**Comment by couchgott** [comment]
i'll do a test deployment with the current setup. 
so you reuse an existing Cert right? ("BBBACMCertArn": "arn:aws:acm:********ACM Cert ARN****************" )

**Comment by ojhaashish13** [comment]
Correct, I am using existing certificates in the actual deployment.
For privacy reasons, I put the stars in my comment here.

**Comment by couchgott** [comment]
when you deploy. can you check at the moment the frontend services are added to the ECS cluster if you see any issues/errors at these task/services. 
This can be checked directly at the ECS cluster. Then select the Tasks and Services deployed and check if the tasks are in a running state. if not (or in a restart cycle) you might see some errors there.

**Comment by ojhaashish13** [comment]
I run the script again with all default parameters except I am using existing hosted zone and existing ACM certificate.
Got this error on the task.
`"CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "871494949924.dkr.ecr.us-west-2.amazonaws.com/bigbluebutton/greenlight:v2": 871494949924.dkr.ecr.us-west-2.amazonaws.com/bigbluebutton/greenlight:v2: not found".`
And found same for scalelite.
I have attached the screenshot for failed tasks and services.

<img width="1182" alt="Screenshot 2021-06-17 at 7 15 15 PM" src="https://user-images.githubusercontent.com/6647624/122498363-fec42200-cfbc-11eb-868f-a21ce8917eca.png">
<img width="1201" alt="Screenshot 2021-06-17 at 7 17 05 PM" src="https://user-images.githubusercontent.com/6647624/122498364-fec42200-cfbc-11eb-9e42-5e98c64ba3ae.png">
<img width="1178" alt="Screenshot 2021-06-17 at 7 23 43 PM" src="https://user-images.githubusercontent.com/6647624/122498366-ff5cb880-cfbc-11eb-9e7a-29f30e0db45c.png">
<img width="1192" alt="Screenshot 2021-06-17 at 7 24 06 PM" src="https://user-images.githubusercontent.com/6647624/122498368-fff54f00-cfbc-11eb-9090-65579ae85a9b.png">

Please let me know how to fix this.

**Comment by couchgott** [comment]
Hey, can you check if the docker images have been pushed to ECR successfully? 
it seems the images are not in place. 
Please also reffer to the requirements and ensure you have docker installed at the device starting the deployment.

**Comment by ojhaashish13** [comment]
Thanks, this solved my problem.
Yes, my docker stopped working after I upgrade to macOS Big Sur. I have reinstalled the docker app and deployment worked.
