### ISSUE TITLE
BBBFontendAppsStack was not successfully created - failed to create: [BBBSMTPUser, BBBScaleliteRole, BBBSESDomainIdentity, BBBPublicCertificate, BBBGreenlightTaskRole, BBBScaleliteALB, BBBFrontendALB

### ISSUE THREAD

**Issue by cnm-michael** [aws-samples/aws-scalable-big-blue-button-example#97]
**Describe the bug**
BBBFontendAppsStack was not successfully created - failed to create: [BBBSMTPUser, BBBScaleliteRole, BBBSESDomainIdentity, BBBPublicCertificate, BBBGreenlightTaskRole, BBBScaleliteALB, BBBFrontendALB

**To Reproduce**
`./setup.sh -p user1 -e my@verified-email.com -h XXYYZZ -s bbb-stack -d mydomain.com`

Stack fails to create with error:

Embedded stack arn:aws:cloudformation:eu-west-1:303507060590:stack/bbb-stack-BBBFontendAppsStack-G1AO932ZMSO7/17b0aa50-ce0e-11eb-80aa-028ffd2cfbdb was not successfully created: The following resource(s) failed to create: [BBBSMTPUser, BBBScaleliteRole, BBBSESDomainIdentity, BBBPublicCertificate, BBBGreenlightTaskRole, BBBScaleliteALB, BBBFrontendALB].

**Expected behavior**
Successful stack creation

**Comment by couchgott** [comment]
can you take a look athe the substack for the frontend and into its events what exactly failed? 
ty!

**Comment by cnm-michael** [comment]
Thanks @couchgott , I investigated the FrontendAppStack sub-stack and turns out that the domain that I was using already had SES set up on it which was blocking the stack from creating it. We decided to use a different domain and everything went through fine. Thank you!

**Comment by couchgott** [comment]
Hey, 
alternatively you could have set the parameter BBBSESValidated to 'true' ;)
