### ISSUE TITLE
Incomplete clean-up process

### ISSUE THREAD

**Issue by jonnyfux** [aws-samples/aws-scalable-big-blue-button-example#98]
**Describe the bug**
The destroy.sh script fails to delete the BBBStackBucket. 

bbb-stack-Sources: DELETE_FAILED | The following resource(s) failed to delete: [BBBStackBucket].
BBBStackBucket: DELETE_FAILED |  The bucket you tried to delete is not empty. You must delete all versions in the bucket.

**To Reproduce**
1. Run setup.sh
2. Run destroy.sh
3. Go Cloudformation dashboard and you will see the error

**Expected behavior**
The BBBStackBucket gets deleted

**Comment by couchgott** [comment]
solved
