### ISSUE TITLE
Can't login into greeenlight

### ISSUE THREAD

**Issue by jonnyfux** [aws-samples/aws-scalable-big-blue-button-example#99]
**Describe the bug**
I installed it using the setup.sh script. Only one parameter in the config was added: BBBSESValidated = true. Everything else was set to the default. Everything finished successfully and I can access the greenlight starting page (conference.mydomain.com)

On login on: conference.mydomain.com with my operator's email and the password from the secret manager ( BBBAdministratorlogin-VJ6JeHXX1Khj) it fails with the error: " The email and password you entered did not match our records. Try again or click Forgot Password to reset your password." 

I also tried to SSH into the server but wasn't sure about which private-key file to use. 

Help is much appreciated. 

**Expected behavior**
I get logged in.

**Comment by couchgott** [comment]
Hey,
sorry for the delay. try to restart the greenlight task at ECS. sometimes it starts too fast and does not handle the initial DB setup (incl. Admin user creation) well. 

let me know if this helps!

**Comment by jonnyfux** [comment]
Hi, 

thanks for your reply!

I have run this command: 
`aws ecs update-service --force-new-deployment --service bbb-stack-BBBFontendAppsStack-1QSB8K3SN4HE4-BBBgreenlightService-wBRlbqsB40hZ --cluster bbb-stack-BBBECSStack-1SU2E1ZA65564-ECSCluster --profile PROFILE_NAME`

And now I can log in without any problems!

**Comment by jonnyfux** [comment]
Just a quick update after multiple deploys. For me, it never works to log in to greenlight after the setup. I always have to run the above-mentioned command. So I would still see this as a bug and not a rarely occurring race condition :D

**Comment by couchgott** [comment]
need to think about a custom start script 

https://github.com/bigbluebutton/greenlight/blob/v2/bin/start

at the moment we do some nasty hack here. which might need optimization: 

- /usr/local/bin/bundle exec rake db:migrate; /usr/local/bin/bundle exec rake user:create["bbbadmin","${ADMIN_LOGIN}","${ADMIN_PASSWORD}","admin"]; bin/start

**Comment by sandeepadda247** [comment]
I am facing the same issue, and it didn't work even after restarting greenlight task at ECS

**Comment by bklein1** [comment]
Can you please share the logs of the Greenlight task?

**Comment by sudra-parth** [comment]
I am also getting the same error. Can you help me from where and in which file I need to configure.

Thanks in advance.

**Comment by sudra-parth** [comment]
The email and password you entered did not match our records. Try again or click Forgot Password to reset your password. 

Is my error.

**Comment by sandeepadda247** [comment]
this is actually not creating the user, so I ssh into server and then added user manually, and it worked

**Comment by sudra-parth** [comment]
> this is actually not creating the user, so I ssh into server and then added user manually, and it worked

How to add manually can you please elaborate? Because I am not able to do that also

**Comment by sandeepadda247** [comment]
you can use rake command 
`/usr/local/bin/bundle exec rake user:create["bbbadmin","${ADMIN_LOGIN}","${ADMIN_PASSWORD}","admin"]`

**Comment by sudra-parth** [comment]
> you can use rake command `/usr/local/bin/bundle exec rake user:create["bbbadmin","${ADMIN_LOGIN}","${ADMIN_PASSWORD}","admin"]`

here showing an error: rake aborted no rakefile found.

May I know in which directory the rake file is stored?

**Comment by sudra-parth** [comment]
Can anyone help me how can access greenlight directory and .env file?
